=== midiacom/eva-robot/EvaML-EvaSIM source code/Linux Version/EvaML-Schema/evaml_schema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!-- ********************** Data type definitions ********************** -->
	<xs:simpleType name="idType">
		<xs:restriction base="xs:ID"/>
	</xs:simpleType>

	<xs:simpleType name="modeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="on"/>
			<xs:enumeration value="off"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="voiceListType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="pt-BR_IsabelaV3Voice"/>
			<xs:enumeration value="en-US_AllisonV3Voice"/>
			<xs:enumeration value="en-US_EmilyV3Voice"/>
			<xs:enumeration value="en-US_HenryV3Voice"/>
			<xs:enumeration value="es-LA_SofiaV3Voice"/>
			<xs:enumeration value="es-ES_EnriqueV3Voice"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="voiceStringType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>

	<xs:simpleType name="voiceType">
		<xs:union memberTypes="voiceListType voiceStringType" />
	</xs:simpleType>

	<xs:simpleType name="audioListType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="applause-moderate"/>
			<xs:enumeration value="beep-09"/>
			<xs:enumeration value="cheering"/>
			<xs:enumeration value="fanfare2"/>
			<xs:enumeration value="laugh-01"/>
			<xs:enumeration value="mario-end-01"/>
			<xs:enumeration value="mario-end-02"/>
			<xs:enumeration value="mario-end-03"/>
			<xs:enumeration value="mario-fundo"/>
			<xs:enumeration value="mario-game-intro"/>
			<xs:enumeration value="mario-sound1"/>
			<xs:enumeration value="mario-sound2"/>
			<xs:enumeration value="mario-start-01"/>
			<xs:enumeration value="mario-start-02"/>
			<xs:enumeration value="oh-no"/>
			<xs:enumeration value="song-exodus"/>
			<xs:enumeration value="song-the-girl-from-ipanema"/>
			<xs:enumeration value="song-the-imperial-march"/>
			<xs:enumeration value="song-vivaldi-spring"/>
			<xs:enumeration value="song-exodus"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="audioStringType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>

	<xs:simpleType name="audioFileType">
		<xs:union memberTypes="audioListType audioStringType" />
	</xs:simpleType>

	<xs:simpleType name="caseOpType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="exact"/>
			<xs:enumeration value="contain"/>
			<xs:enumeration value="eq"/>
			<xs:enumeration value="lt"/>
			<xs:enumeration value="gt"/>
			<xs:enumeration value="lte"/>
			<xs:enumeration value="gte"/>
			<xs:enumeration value="ne"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="audioBlockType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="true"/>
			<xs:enumeration value="false"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="ledAnimationType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="happy"/>
			<xs:enumeration value="sad"/>
			<xs:enumeration value="angry"/>
			<xs:enumeration value="stop"/>
			<xs:enumeration value="speak"/>
			<xs:enumeration value="listen"/>
			<xs:enumeration value="surprise"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="lightStateType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="on"/>
			<xs:enumeration value="off"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="lightRgbColorType">
		<xs:restriction base="xs:token">
			<xs:pattern value="#[\dA-F | a-f ]{6}([\dA-F | a-f][\dA-F | a-f])?"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="lightListColorType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="white"/>
			<xs:enumeration value="black"/>
			<xs:enumeration value="red"/>
			<xs:enumeration value="pink"/>
			<xs:enumeration value="green"/>
			<xs:enumeration value="yellow"/>
			<xs:enumeration value="blue"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="lightColorType">
		<xs:union memberTypes="lightListColorType lightRgbColorType" />
	</xs:simpleType>

	<xs:simpleType name="counterOpType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="="/>
			<xs:enumeration value="+"/>
			<xs:enumeration value="*"/>
			<xs:enumeration value="/"/>
			<xs:enumeration value="%"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="evaEmotionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="neutral"/>
			<xs:enumeration value="happy"/>
			<xs:enumeration value="sad"/>
			<xs:enumeration value="angry"/>
		</xs:restriction>
	</xs:simpleType>

  <!-- ********************** EvaML Commands Definitions ********************** -->
	<xs:element name="random">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="min" type="xs:nonNegativeInteger" use="required"/>
			<xs:attribute name="max" type="xs:nonNegativeInteger" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="wait">
	  <xs:complexType>
		<xs:attribute name="id" type="idType"/>
	    <xs:attribute name="duration" type="xs:nonNegativeInteger" use="required"/>
	  </xs:complexType>
	</xs:element>

	<xs:element name="talk">
		<xs:complexType mixed="true">
			<xs:attribute name="id" type="idType"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="stop">
		<xs:complexType>
		</xs:complexType>
	</xs:element>

	<xs:element name="light">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="state" type="lightStateType" use="required"/>
			<xs:attribute name="color" type="lightColorType" default="white"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="goto">
		<xs:complexType>
			<xs:attribute name="target" type="xs:IDREF" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="userEmotion">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="evaEmotion">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="emotion" type="evaEmotionType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="useMacro">
		<xs:complexType>
			<xs:attribute name="macro" type="xs:IDREF" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="listen">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="audio">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="source" type="audioFileType" use="required"/>
			<xs:attribute name="block" type="audioBlockType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="led">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="animation" type="ledAnimationType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="counter">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="var" type="xs:string" use="required"/>
			<xs:attribute name="op" type="counterOpType" use="required"/>
			<xs:attribute name="value" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="switch">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="case" minOccurs="1" maxOccurs="unbounded" />
				<xs:element ref="default" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="var" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="voice">
		<xs:complexType>
			<xs:attribute name="tone" type="voiceType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="lightEffects">
		<xs:complexType>
			<xs:attribute name="mode" type="modeType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="audioEffects">
		<xs:complexType>
			<xs:attribute name="mode" type="modeType" use="required"/>
			<xs:attribute name="vol" type="xs:string" default="100%"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="case">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="random"/>
				<xs:element ref="wait"/>
				<xs:element ref="talk"/>
				<xs:element ref="stop"/>
				<xs:element ref="light"/>
				<xs:element ref="goto"/>
				<xs:element ref="userEmotion"/>
				<xs:element ref="evaEmotion"/>
				<xs:element ref="useMacro"/>
				<xs:element ref="listen"/>
				<xs:element ref="audio"/>
				<xs:element ref="led"/>
				<xs:element ref="counter"/>
				<xs:element ref="switch"/>
			</xs:choice>
			<xs:attribute name="op" type="caseOpType" use="required"/>
			<xs:attribute name="value" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="default">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="random"/>
				<xs:element ref="wait"/>
				<xs:element ref="talk"/>
				<xs:element ref="stop"/>
				<xs:element ref="light"/>
				<xs:element ref="goto"/>
				<xs:element ref="userEmotion"/>
				<xs:element ref="evaEmotion"/>
				<xs:element ref="useMacro"/>
				<xs:element ref="listen"/>
				<xs:element ref="audio"/>
				<xs:element ref="led"/>
				<xs:element ref="counter"/>
				<xs:element ref="switch"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="macro">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="random"/>
				<xs:element ref="wait"/>
				<xs:element ref="talk"/>
				<xs:element ref="stop"/>
				<xs:element ref="light"/>
				<xs:element ref="goto"/>
				<xs:element ref="userEmotion"/>
				<xs:element ref="evaEmotion"/>
				<xs:element ref="listen"/>
				<xs:element ref="audio"/>
				<xs:element ref="led"/>
				<xs:element ref="counter"/>
				<xs:element ref="switch"/>
			</xs:choice>
			<xs:attribute name="id" type="idType" use="required" />
		</xs:complexType>
	</xs:element>

	<!-- ********************** Root Section Definition ********************** -->
	<xs:element name="evaml">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="settings"/>
				<xs:element ref="script"/>
				<xs:element ref="macros" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<!-- ********************** Settings Section Definition ********************** -->
	<xs:element name="settings">
    <xs:complexType>
			<xs:all>
				<xs:element ref="voice" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="lightEffects" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="audioEffects" minOccurs="0" maxOccurs="1"/>
			</xs:all>
    </xs:complexType>
  </xs:element>

	<!-- ********************** Script Section Definition ********************** -->
	<xs:element name="script">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="random"/>
				<xs:element ref="wait"/>
				<xs:element ref="talk"/>
				<xs:element ref="stop"/>
				<xs:element ref="light"/>
				<xs:element ref="goto"/>
				<xs:element ref="userEmotion"/>
				<xs:element ref="evaEmotion"/>
				<xs:element ref="useMacro"/>
				<xs:element ref="listen"/>
				<xs:element ref="audio"/>
				<xs:element ref="led"/>
				<xs:element ref="counter"/>
				<xs:element ref="switch"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<!-- ********************** Macros Section Definition ********************** -->
	<xs:element name="macros">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="macro"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== midiacom/eva-robot/EvaML-EvaSIM/imitation-game-english.xml
<?xml version="1.0" encoding="UTF-8"?>
<evaml name="imitation-game-english"
  xsi:noNamespaceSchemaLocation="/home/marcelo/Dropbox/Estudo XML/EvaML-Schema/evaml_schema.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <settings>
      <voice tone="en-US_AllisonV3Voice" />
      <lightEffects mode="on" />
      <audioEffects mode="on" vol="100%" />
    </settings>
    <script>
      <!-- tarefa (parte 01) *********************************************************************** -->
      <evaEmotion emotion="neutral" />
      <light state="on" color="white" />
      <audio source="mario-start-01" block="true" />
      <light state="on" color="yellow" />
      <evaEmotion emotion="happy" />
      <talk>Hi, I'm the robot Eva / Hello, my name is Eva / Hi, what is up. I am the robot Eva</talk>
      <light state="on" color="pink" />
      <evaEmotion emotion="neutral" />
      <wait duration="2000" />
      <!-- tarefa (parte 02) ************************************************************************* -->
      <talk>What is your name?</talk>
      <listen />
      <talk>Hello $, I'm going to present my expressions</talk>
      <evaEmotion emotion="happy"/>
      <talk>I can express happiness</talk>
      <evaEmotion emotion="sad"/>
      <talk>I can express sadness</talk> 
      <evaEmotion emotion="angry"/>
      <talk>I can express anger</talk>
      <evaEmotion emotion="neutral"/>
      <talk>Hey $, let's play the emotions game?</talk>
      <listen />
      <switch var="$">
        <case op="contain" value="yes">
          <evaEmotion emotion="happy" />
          <talk>Excelent! Let's go now</talk>
        </case>
        <case op="contain" value="no">
          <evaEmotion emotion="sad" />
          <talk>Oh, I'm sorry you don't want to play. Bye!</talk>
          <light state="off" />
          <stop />
        </case>
      </switch>
      <!-- tarefa (parte 03) ************************************************************************* -->
      <talk>I will show some emotions and you try to imitate me</talk>
      <counter var="score" op="=" value="0" />
      <counter var="chance" op="=" value="0" />
      <random id = "LOOP" min="1" max="3" />
      <switch var="$">
        <case op="eq" value="1">
          <evaEmotion emotion="sad" />
          <light state="on" color="blue" />
          <useMacro macro="GET_EXPRESSION" />
          <switch var="$">
            <case op="exact" value="sad">
              <useMacro macro="RIGHT_ANSWER" />
            </case>
            <default>
              <useMacro macro="WRONG_ANSWER" />
            </default>
          </switch>
        </case>
        <case op="eq" value="2">
          <evaEmotion emotion="happy" />
          <light state="on" color="yellow" />
          <useMacro macro="GET_EXPRESSION" />
          <switch var="$">
            <case op="exact" value="happy">
              <useMacro macro="RIGHT_ANSWER" />
            </case>
            <default>
              <useMacro macro="WRONG_ANSWER" />
            </default>
          </switch>
        </case>
        <case op="eq" value="3">
          <evaEmotion emotion="angry" />
          <light state="on" color="red" />
          <useMacro macro="GET_EXPRESSION" />
          <switch var="$">
            <case op="exact" value="angry">
              <useMacro macro="RIGHT_ANSWER" />
            </case>
            <default>
              <useMacro macro="WRONG_ANSWER" />
            </default>
          </switch>
        </case>
      </switch>
      <counter var="chance" op="+" value="1" />
      <switch var="chance">
        <case op="eq" value="3">
          <evaEmotion emotion="happy" />
          <talk>Your score was #score</talk>
          <talk>It was good to play with you $1. Bye</talk>
          <light state="off" />
          <stop />
        </case>
        <default>
          <goto target="LOOP" />
        </default>
      </switch>
  </script>
  <macros>
    <!-- Usada na tarefa 3 -->
    <macro id="GET_EXPRESSION">
      <talk>Can you imitate me?</talk>
      <audio source="mario-fundo" block="false" />
      <userEmotion />
    </macro>
    <!-- Usada na tarefa 3 -->
    <macro id="RIGHT_ANSWER">
      <evaEmotion emotion="happy" />
      <audio source="fanfare2" block="true" />
      <talk>Ok! You are correct</talk>
      <counter var="score" op="+" value="1" />
    </macro>
    <!-- Usada na tarefa 3 -->
    <macro id="WRONG_ANSWER">
      <evaEmotion emotion="sad" />
      <talk>You are wrong</talk>
    </macro>
  </macros>
</evaml>

=== midiacom/eva-robot/EvaML-EvaSIM source code/Linux Version/_macros.xml
<evaml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="script01" xsi:noNamespaceSchemaLocation="EvaML-Schema/evaml_schema.xsd">
  <settings>
    <voice tone="pt-BR_IsabelaV3Voice" />
  </settings>
  <script>
    <evaEmotion emotion="NEUTRAL" />
      <light state="ON" />
      <talk>Olá eu sou o robô Eva</talk>
      <audio source="fanfare2" block="TRUE" />
      <talk>Qual o seu nome?</talk>
      <listen />
    <talk>Muito prazer $</talk>
    <talk>Três variáveis serão criadas. Olha na tabela ao lado </talk>
    <counter var="var1" op="=" value="0" />
      <counter var="var2" op="=" value="0" />
      <counter var="var3" op="=" value="0" />
    <random min="1" max="3" />
    <talk>Veja como estou me sentindo hoje</talk>
    <switch var="$">
      <case op="exact" value="1">
        <evaEmotion emotion="SAD" />
        <light state="ON" color="BLUE" />
        <talk>Estou triste</talk>
        <motion type="2DOWN" />
        <talk>Vou incrementar a variável var 1 em uma unidade</talk>
        <counter var="var1" op="+" value="1" />
      </case>
      <case op="exact" value="2">
        <evaEmotion emotion="ANGRY" />
        <light state="ON" color="RED" />
        <talk>Estou com raiva</talk>
        <motion type="2DOWN" />
        <talk>Vou incrementar a variável var 2 em duas unidades</talk>
        <counter var="var2" op="+" value="2" />
      </case>
      <case op="exact" value="3">
        <evaEmotion emotion="HAPPY" />
        <light state="ON" color="GREEN" />
        <talk>Estou muito feliz</talk>
        <motion type="2UP" />
        <talk>Vou incrementar a variável var 3 em três unidades</talk>
        <counter var="var3" op="+" value="3" />
      </case>
    </switch>
    <evaEmotion emotion="NEUTRAL" />
    <talk>Ouça essa música e me diga como você está se sentindo</talk>
    <audio source="song-vivaldi-spring" block="FALSE" />
    <listen />
    <talk>Nossa você está $</talk>
      <talk>Até mais, $1</talk>
      <light state="OFF" />
    </script>
  </evaml>

=== midiacom/eva-robot/EvaML-EvaSIM source code/Linux Version/teste4.xml
<?xml version="1.0" encoding="UTF-8"?>
<evaml
  name="teste4"
  xsi:noNamespaceSchemaLocation="EvaML-Schema/evaml_schema.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <settings>
      <voice tone="en-US_AllisonV3Voice" />
      <lightEffects mode="OFF" />
      <audioEffects mode="OFF" />
    </settings>
    <script>
      <evaEmotion emotion="NEUTRAL" />
      <wait duration="1000" />
      <evaEmotion emotion="ANGRY" />
      <wait duration="1000" />
      <evaEmotion emotion="HAPPY" />
      <wait duration="1000" />
      <evaEmotion emotion="SAD" />
      <wait duration="1000" />
      <audio source="applause-moderate" block="TRUE" />
    </script>
</evaml>

=== midiacom/eva-robot/EvaML-EvaSIM/game-of-colors-english.xml
<?xml version="1.0" encoding="UTF-8"?>
<evaml name="game-of-colors-english"
	xsi:noNamespaceSchemaLocation="/home/marcelo/Dropbox/Estudo XML/EvaML-Schema/evaml_schema.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<settings>
		<voice tone="en-US_AllisonV3Voice" />
	</settings>
	<script>
		<light state="off" />
		<evaEmotion emotion="neutral" />
		<talk>Hi, I'm the robot Eva!</talk>
		<audio source="mario-game-intro" block="true" />
		<talk>Shall we play the color game?</talk>
		<evaEmotion emotion="happy" />
		<audio source="mario-start-01" block="true" />
		<talk>What's your name?</talk>
		<audio source="mario-sound1" block="true" />
		<listen />
		<talk>That Cool!</talk>
		<talk>Let's go $</talk>
		<!-- ############ Primeira cor com duas tentativas ############ -->
		<counter var="try" op="=" value="1" />
		<evaEmotion id="COR1" emotion="neutral" />
		<talk>What is this color?</talk>
		<audio source="mario-sound1" block="true" />
		<light state="on" color="blue" />
		<listen />
		<switch var="$">
			<case op="contain" value="blue">
				<audio source="mario-start-02" block="true" />
				<talk>Very good! You're right!</talk>
			</case>
			<default>
				<audio source="mario-sound1" block="true" />
				<talk>This color is blue</talk>
				<switch var="try">
					<case op="eq" value="1">
						<counter var="try" op="+" value="1" />
						<wait duration="2000" />
						<talk>Let's try one more time</talk>
						<light state="off" />
						<wait duration="2000" />
						<goto target="COR1" />
					</case>
					<case op="eq" value="2">
						<wait duration="100" />
					</case>
				</switch>
			</default>
		</switch>
		<evaEmotion emotion="happy" />
		<light state="off" />
		<wait duration="1000" />
		<!-- ############ Segunda cor com duas tentativas ############ -->
		<counter var="try" op="=" value="1" />
		<evaEmotion id="COR2" emotion="neutral" />
		<talk>What is this color?</talk>
		<audio source="mario-sound1" block="true" />
		<light state="on" color="red" />
		<listen />
		<switch var="$">
			<case op="contain" value="red">
				<audio source="mario-start-02" block="true" />
				<talk>Excelent! You're right!</talk>
			</case>
			<default>
				<audio source="mario-sound1" block="true" />
				<talk>This color is red</talk>
				<switch var="try">
					<case op="eq" value="1">
						<counter var="try" op="+" value="1" />
						<wait duration="2000" />
						<talk>Let's try one more time</talk>
						<light state="off" />
						<wait duration="2000" />
						<goto target="COR2" />
					</case>
					<case op="eq" value="2">
						<wait duration="100" />
					</case>
				</switch>
			</default>
		</switch>
		<evaEmotion emotion="happy" />
		<light state="off" />
		<wait duration="1000" />
		<!-- ############ Terceira cor com duas tentativas ############ -->
		<counter var="try" op="=" value="1" />
		<evaEmotion id="COR3" emotion="neutral" />
		<talk>What is this color?</talk>
		<audio source="mario-sound1" block="true" />
		<light state="on" color="green" />
		<listen />
		<switch var="$">
			<case op="contain" value="green">
				<audio source="mario-start-02" block="true" />
				<talk>Nice! You're correct!</talk>
			</case>
			<default>
				<audio source="mario-sound1" block="true" />
				<talk>This color is green</talk>
				<switch var="try">
					<case op="eq" value="1">
						<counter var="try" op="+" value="1" />
						<wait duration="2000" />
						<talk>Let's try one more time</talk>
						<light state="off" />
						<wait duration="2000" />
						<goto target="COR3" />
					</case>
					<case op="eq" value="2">
						<wait duration="100" />
					</case>
				</switch>
			</default>
		</switch>
		<evaEmotion emotion="happy" />
		<talk>It was really nice to play with you $1</talk>
		<audio source="mario-end-02" block="true" />
		<light state="off" />
	</script>
</evaml>

=== midiacom/eva-robot/EvaML-EvaSIM/game-of-emotions-english-ok.xml
<?xml version="1.0" encoding="UTF-8"?>
<evaml name="game-of-emotions-english-ok"
	xsi:noNamespaceSchemaLocation="/home/marcelo/Dropbox/Estudo XML/EvaML-Schema/evaml_schema.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<settings>
		<voice tone="en-US_AllisonV3Voice" />
	</settings>
	<script>
		<!-- Saudação e apresentação do jogo-->
		<light state="on" color="white" />
		<evaEmotion emotion="neutral" />
		<talk>Hi, I am the robot Eva!</talk>
		<audio source="mario-game-intro" block="true" />
		<talk>Shall we play the emotions game?</talk>
		<evaEmotion emotion="happy" />
		<audio source="mario-start-01" block="true" />
		<evaEmotion emotion="neutral" />
		<talk>What is your name?</talk>
		<audio source="mario-sound1" block="false" />
		<listen />
		<evaEmotion emotion="happy" />
		<talk>Very nice!</talk>
		<talk>Let's go $</talk>
		<evaEmotion emotion="neutral" />
		<talk>I will show you my emotions</talk>
		<audio source="mario-sound1" block="true" />
		<talk>I look like this when I am happy</talk>
		<evaEmotion emotion="happy" />
		<light state="on" color="green" />
		<led animation="happy" />
		<wait duration="2000" />
		<evaEmotion emotion="neutral" />
		<talk>I look like this when I am sad</talk>
		<audio source="mario-sound1" block="true" />
		<evaEmotion emotion="sad" />
		<light state="on" color="blue" />
		<led animation="sad" />
		<wait duration="2000" />
		<evaEmotion emotion="neutral" />
		<talk>I look like this when I am angry</talk>
		<audio source="mario-sound1" block="false" />
		<evaEmotion emotion="angry" />
		<light state="on" color="red" />
		<led animation="angry" />
		<wait duration="2000" />
		<evaEmotion emotion="neutral" />
		<light state="on" color="white" />
		<talk>Let's start the game</talk>
		<!-- ############ Primeira emoção com duas tentativas ############ -->
		<counter var="try" op="=" value="1" />
		<evaEmotion id="EMOCAO1" emotion="neutral" />
		<light state="on" color="white" />
		<talk>How am I feeling?</talk>
		<talk>Happy, sad, or, angry?</talk>
		<evaEmotion emotion="sad" />
		<light state="on" color="blue" />
		<audio source="mario-sound1" block="true" />
		<listen />
		<switch var="$">
			<case op="contain" value="sad">
				<audio source="mario-start-02" block="true" />
				<talk>Very good! You are right!</talk>
			</case>
			<default>
				<audio source="mario-sound1" block="true" />
				<talk>I am feeling sad</talk>
				<switch var="try">
					<case op="eq" value="1">
						<counter var="try" op="+" value="1" />
						<wait duration="2000" />
						<talk>Let's try one more time</talk>
						<wait duration="2000" />
						<goto target="EMOCAO1" />
					</case>
					<case op="eq" value="2">
						<wait duration="100" />
					</case>
				</switch>
			</default>
		</switch>
		<evaEmotion emotion="happy" />
		<wait duration="1000" />
		<!-- ############ Segunda emoção com duas tentativas ############ -->
		<counter var="try" op="=" value="1" />
		<evaEmotion id="EMOCAO2" emotion="neutral" />
		<light state="on" color="white" />
		<talk>How am I feeling?</talk>
		<talk>Happy, sad, or, angry?</talk>
		<evaEmotion emotion="angry" />
		<light state="on" color="red" />
		<audio source="mario-sound1" block="true" />
		<listen />
		<switch var="$">
			<case op="contain" value="angry">
				<audio source="mario-start-02" block="true" />
				<talk>Nice! You are right!</talk>
			</case>
			<default>
				<audio source="mario-sound1" block="true" />
				<talk>I am feeling angry</talk>
				<switch var="try">
					<case op="eq" value="1">
						<counter var="try" op="+" value="1" />
						<wait duration="2000" />
						<talk>Let's try one more time</talk>
						<wait duration="2000" />
						<goto target="EMOCAO2" />
					</case>
					<case op="eq" value="2">
						<wait duration="100" />
					</case>
				</switch>
			</default>
		</switch>
		<evaEmotion emotion="happy" />
		<wait duration="1000" />
		<!-- ############ Terceira emoção com duas tentativas ############ -->
		<counter var="try" op="=" value="1" />
		<evaEmotion id="EMOCAO3" emotion="neutral" />
		<light state="on" color="white" />
		<talk>How am I feeling?</talk>
		<talk>Happy, sad, or, angry?</talk>
		<evaEmotion emotion="happy" />
		<light state="on" color="green" />
		<audio source="mario-sound1" block="true" />
		<listen />
		<switch var="$">
			<case op="contain" value="happy">
				<audio source="mario-start-02" block="true" />
				<talk>Perfect! You are correct!</talk>
			</case>
			<default>
				<audio source="mario-sound1" block="true" />
				<talk>I am feeling happy</talk>
				<switch var="try">
					<case op="eq" value="1">
						<counter var="try" op="+" value="1" />
						<wait duration="2000" />
						<talk>Let's try one more time</talk>
						<wait duration="2000" />
						<goto target="EMOCAO2" />
					</case>
					<case op="eq" value="2">
						<wait duration="100" />
					</case>
				</switch>
			</default>
		</switch>
		<evaEmotion emotion="happy" />
		<talk>It was really nice to play with you $1</talk>
		<audio source="mario-end-02" block="true" />
		<light state="off" />
	</script>
</evaml>
