=== midiacom/eva-robot/EvaML-EvaSIM source code/Linux Version/EvaML-Schema/evaml_schema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!-- ********************** Data type definitions ********************** -->
	<xs:simpleType name="idType">
		<xs:restriction base="xs:ID"/>
	</xs:simpleType>

	<xs:simpleType name="modeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="on"/>
			<xs:enumeration value="off"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="voiceListType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="pt-BR_IsabelaV3Voice"/>
			<xs:enumeration value="en-US_AllisonV3Voice"/>
			<xs:enumeration value="en-US_EmilyV3Voice"/>
			<xs:enumeration value="en-US_HenryV3Voice"/>
			<xs:enumeration value="es-LA_SofiaV3Voice"/>
			<xs:enumeration value="es-ES_EnriqueV3Voice"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="voiceStringType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>

	<xs:simpleType name="voiceType">
		<xs:union memberTypes="voiceListType voiceStringType" />
	</xs:simpleType>

	<xs:simpleType name="audioListType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="applause-moderate"/>
			<xs:enumeration value="beep-09"/>
			<xs:enumeration value="cheering"/>
			<xs:enumeration value="fanfare2"/>
			<xs:enumeration value="laugh-01"/>
			<xs:enumeration value="mario-end-01"/>
			<xs:enumeration value="mario-end-02"/>
			<xs:enumeration value="mario-end-03"/>
			<xs:enumeration value="mario-fundo"/>
			<xs:enumeration value="mario-game-intro"/>
			<xs:enumeration value="mario-sound1"/>
			<xs:enumeration value="mario-sound2"/>
			<xs:enumeration value="mario-start-01"/>
			<xs:enumeration value="mario-start-02"/>
			<xs:enumeration value="oh-no"/>
			<xs:enumeration value="song-exodus"/>
			<xs:enumeration value="song-the-girl-from-ipanema"/>
			<xs:enumeration value="song-the-imperial-march"/>
			<xs:enumeration value="song-vivaldi-spring"/>
			<xs:enumeration value="song-exodus"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="audioStringType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>

	<xs:simpleType name="audioFileType">
		<xs:union memberTypes="audioListType audioStringType" />
	</xs:simpleType>

	<xs:simpleType name="caseOpType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="exact"/>
			<xs:enumeration value="contain"/>
			<xs:enumeration value="eq"/>
			<xs:enumeration value="lt"/>
			<xs:enumeration value="gt"/>
			<xs:enumeration value="lte"/>
			<xs:enumeration value="gte"/>
			<xs:enumeration value="ne"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="audioBlockType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="true"/>
			<xs:enumeration value="false"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="ledAnimationType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="happy"/>
			<xs:enumeration value="sad"/>
			<xs:enumeration value="angry"/>
			<xs:enumeration value="stop"/>
			<xs:enumeration value="speak"/>
			<xs:enumeration value="listen"/>
			<xs:enumeration value="surprise"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="lightStateType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="on"/>
			<xs:enumeration value="off"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="lightRgbColorType">
		<xs:restriction base="xs:token">
			<xs:pattern value="#[\dA-F | a-f ]{6}([\dA-F | a-f][\dA-F | a-f])?"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="lightListColorType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="white"/>
			<xs:enumeration value="black"/>
			<xs:enumeration value="red"/>
			<xs:enumeration value="pink"/>
			<xs:enumeration value="green"/>
			<xs:enumeration value="yellow"/>
			<xs:enumeration value="blue"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="lightColorType">
		<xs:union memberTypes="lightListColorType lightRgbColorType" />
	</xs:simpleType>

	<xs:simpleType name="counterOpType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="="/>
			<xs:enumeration value="+"/>
			<xs:enumeration value="*"/>
			<xs:enumeration value="/"/>
			<xs:enumeration value="%"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="evaEmotionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="neutral"/>
			<xs:enumeration value="happy"/>
			<xs:enumeration value="sad"/>
			<xs:enumeration value="angry"/>
		</xs:restriction>
	</xs:simpleType>

  <!-- ********************** EvaML Commands Definitions ********************** -->
	<xs:element name="random">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="min" type="xs:nonNegativeInteger" use="required"/>
			<xs:attribute name="max" type="xs:nonNegativeInteger" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="wait">
	  <xs:complexType>
		<xs:attribute name="id" type="idType"/>
	    <xs:attribute name="duration" type="xs:nonNegativeInteger" use="required"/>
	  </xs:complexType>
	</xs:element>

	<xs:element name="talk">
		<xs:complexType mixed="true">
			<xs:attribute name="id" type="idType"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="stop">
		<xs:complexType>
		</xs:complexType>
	</xs:element>

	<xs:element name="light">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="state" type="lightStateType" use="required"/>
			<xs:attribute name="color" type="lightColorType" default="white"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="goto">
		<xs:complexType>
			<xs:attribute name="target" type="xs:IDREF" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="userEmotion">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="evaEmotion">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="emotion" type="evaEmotionType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="useMacro">
		<xs:complexType>
			<xs:attribute name="macro" type="xs:IDREF" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="listen">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="audio">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="source" type="audioFileType" use="required"/>
			<xs:attribute name="block" type="audioBlockType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="led">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="animation" type="ledAnimationType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="counter">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="var" type="xs:string" use="required"/>
			<xs:attribute name="op" type="counterOpType" use="required"/>
			<xs:attribute name="value" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="switch">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="case" minOccurs="1" maxOccurs="unbounded" />
				<xs:element ref="default" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="var" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="voice">
		<xs:complexType>
			<xs:attribute name="tone" type="voiceType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="lightEffects">
		<xs:complexType>
			<xs:attribute name="mode" type="modeType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="audioEffects">
		<xs:complexType>
			<xs:attribute name="mode" type="modeType" use="required"/>
			<xs:attribute name="vol" type="xs:string" default="100%"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="case">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="random"/>
				<xs:element ref="wait"/>
				<xs:element ref="talk"/>
				<xs:element ref="stop"/>
				<xs:element ref="light"/>
				<xs:element ref="goto"/>
				<xs:element ref="userEmotion"/>
				<xs:element ref="evaEmotion"/>
				<xs:element ref="useMacro"/>
				<xs:element ref="listen"/>
				<xs:element ref="audio"/>
				<xs:element ref="led"/>
				<xs:element ref="counter"/>
				<xs:element ref="switch"/>
			</xs:choice>
			<xs:attribute name="op" type="caseOpType" use="required"/>
			<xs:attribute name="value" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="default">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="random"/>
				<xs:element ref="wait"/>
				<xs:element ref="talk"/>
				<xs:element ref="stop"/>
				<xs:element ref="light"/>
				<xs:element ref="goto"/>
				<xs:element ref="userEmotion"/>
				<xs:element ref="evaEmotion"/>
				<xs:element ref="useMacro"/>
				<xs:element ref="listen"/>
				<xs:element ref="audio"/>
				<xs:element ref="led"/>
				<xs:element ref="counter"/>
				<xs:element ref="switch"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="macro">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="random"/>
				<xs:element ref="wait"/>
				<xs:element ref="talk"/>
				<xs:element ref="stop"/>
				<xs:element ref="light"/>
				<xs:element ref="goto"/>
				<xs:element ref="userEmotion"/>
				<xs:element ref="evaEmotion"/>
				<xs:element ref="listen"/>
				<xs:element ref="audio"/>
				<xs:element ref="led"/>
				<xs:element ref="counter"/>
				<xs:element ref="switch"/>
			</xs:choice>
			<xs:attribute name="id" type="idType" use="required" />
		</xs:complexType>
	</xs:element>

	<!-- ********************** Root Section Definition ********************** -->
	<xs:element name="evaml">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="settings"/>
				<xs:element ref="script"/>
				<xs:element ref="macros" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<!-- ********************** Settings Section Definition ********************** -->
	<xs:element name="settings">
    <xs:complexType>
			<xs:all>
				<xs:element ref="voice" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="lightEffects" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="audioEffects" minOccurs="0" maxOccurs="1"/>
			</xs:all>
    </xs:complexType>
  </xs:element>

	<!-- ********************** Script Section Definition ********************** -->
	<xs:element name="script">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="random"/>
				<xs:element ref="wait"/>
				<xs:element ref="talk"/>
				<xs:element ref="stop"/>
				<xs:element ref="light"/>
				<xs:element ref="goto"/>
				<xs:element ref="userEmotion"/>
				<xs:element ref="evaEmotion"/>
				<xs:element ref="useMacro"/>
				<xs:element ref="listen"/>
				<xs:element ref="audio"/>
				<xs:element ref="led"/>
				<xs:element ref="counter"/>
				<xs:element ref="switch"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<!-- ********************** Macros Section Definition ********************** -->
	<xs:element name="macros">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="macro"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== midiacom/eva-robot/EvaML-EvaSIM source code/game-of-emotions-ING.xml
<?xml version="1.0" encoding="UTF-8"?>
<evaml name="game-of-emotions-ING"
	xsi:noNamespaceSchemaLocation="/home/marcelo/Dropbox/Estudo XML/EvaML-Schema/evaml_schema.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<settings>
		<voice tone="en-US_AllisonV3Voice" />
	</settings>
	<script>
		<light state="on" color="white" />
		<evaEmotion emotion="neutral" />
		<talk>Hi, I am the robot Eva!</talk>
		<audio source="mario-game-intro" block="true" />
		<talk>Shall we play the emotions game?</talk>
		<evaEmotion emotion="happy" />
		<audio source="mario-start-01" block="true" />
		<evaEmotion emotion="neutral" />
		<talk>What is your name?</talk>
		<audio source="mario-sound1" block="true" />
			<led animation="listen" />
			<wait duration="4000" />
			<led animation="stop" />
			<wait duration="1000" />
		<evaEmotion emotion="happy" />
		<talk>Very nice!</talk>
		<talk>Let's go Marcelo</talk>
		<evaEmotion emotion="neutral" />
		<talk>I will show you my emotions</talk>
		<audio source="mario-sound1" block="true" />
		<talk>I look like this when I am happy</talk>
		<evaEmotion emotion="happy" />
		<light state="on" color="green" />
		<led animation="happy" />
		<wait duration="2000" />
		<evaEmotion emotion="neutral" />
		<talk>I look like this when I am sad</talk>
		<audio source="mario-sound1" block="true" />
		<evaEmotion emotion="sad" />
		<light state="on" color="blue" />
		<led animation="sad" />
		<wait duration="2000" />
		<evaEmotion emotion="neutral" />
		<talk>I look like this when I am angry</talk>
		<audio source="mario-sound1" block="true" />
		<evaEmotion emotion="angry" />
		<light state="on" color="red" />
		<led animation="angry" />
		<wait duration="2000" />
		<evaEmotion emotion="neutral" />
		<light state="on" color="white" />
		<talk>Let's start the game</talk>
		<!-- ############ Primeira emoção com duas tentativas ############ -->
		<counter var="try" op="=" value="1" />
		<evaEmotion id="EMOCAO1" emotion="neutral" />
		<light state="on" color="white" />
		<talk>How am I feeling?</talk>
		<talk>Happy, sad, or, angry?</talk>
		<evaEmotion emotion="sad" />
		<light state="on" color="blue" />
		<audio source="mario-sound1" block="true" />
			<led animation="listen" />
			<wait duration="4000" />
			<led animation="stop" />
			<wait duration="1000" />
				<audio source="mario-start-02" block="true" />
				<talk>Very good! You are right!</talk>
			
		<evaEmotion emotion="happy" />
		<wait duration="1000" />
		<!-- ############ Segunda emoção com duas tentativas ############ -->
		<counter var="try" op="=" value="1" />
		<evaEmotion id="EMOCAO2" emotion="neutral" />
		<light state="on" color="white" />
		<talk>How am I feeling?</talk>
		<talk>Happy, sad, or, angry?</talk>
		<evaEmotion emotion="angry" />
		<light state="on" color="red" />
		<audio source="mario-sound1" block="true" />
			<led animation="listen" />
			<wait duration="4000" />
			<led animation="stop" />
			<wait duration="1000" />
			<audio source="mario-start-02" block="true" />
			<talk>Nice! You are right!</talk>
			
		<evaEmotion emotion="happy" />
		<wait duration="1000" />
		<!-- ############ Terceira emoção com duas tentativas ############ -->
		<counter var="try" op="=" value="1" />
		<evaEmotion id="EMOCAO3" emotion="neutral" />
		<light state="on" color="white" />
		<talk>How am I feeling?</talk>
		<talk>Happy, sad, or, angry?</talk>
		<evaEmotion emotion="happy" />
		<light state="on" color="green" />
		<audio source="mario-sound1" block="true" />
			<led animation="listen" />
			<wait duration="4000" />
			<led animation="stop" />
			<wait duration="1000" />
		
				<audio source="mario-sound1" block="true" />
				<talk>I am feeling happy</talk>
						<wait duration="2000" />
						<talk>Let's try one more time</talk>
						<wait duration="2000" />
						<evaEmotion emotion="neutral" />
						<light state="on" color="white" />
						<talk>How am I feeling?</talk>
						<talk>Happy, sad, or, angry?</talk>
						<evaEmotion emotion="happy" />
						<light state="on" color="green" />
						<audio source="mario-sound1" block="true" />
							<led animation="listen" />
							<wait duration="4000" />
							<led animation="stop" />
							<wait duration="1000" />
							<audio source="mario-start-02" block="true" />
							<talk>Perfect! You are correct </talk>
		<evaEmotion emotion="happy" />
		<talk>It was really nice to play with you Marcelo</talk>
		<audio source="mario-end-02" block="true" />
		<light state="off" />
	</script>
</evaml>

=== midiacom/eva-robot/EvaML-EvaSIM source code/Windows Version/_node_keys.xml
<evaml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="teste4" xsi:noNamespaceSchemaLocation="EvaML-Schema/evaml_schema.xsd" id="73bf3127fb3c9791e88a4d308171fd85">
  <settings>
      <voice tone="en-US_AllisonV3Voice" key="1000" />
      <lightEffects mode="OFF" />
      <audioEffects mode="ON" />
    </settings>
    <script>
      <light state="ON" color="RED" key="1001" />
      <wait duration="1000" key="1002" />
      <light state="ON" color="BLACK" key="1003" />
      <wait duration="1000" key="1004" />
      <light state="ON" color="BLUE" key="1005" />
      <wait duration="1000" key="1006" />
      <light state="ON" color="GREEN" key="1007" />
      <wait duration="1000" key="1008" />
      <light state="ON" color="PINK" key="1009" />
      <wait duration="1000" key="1010" />
      <light state="ON" color="WHITE" key="1011" />
      <wait duration="1000" key="1012" />
      <light state="ON" color="YELLOW" key="1013" />
      <wait duration="1000" key="1014" />
    </script>
</evaml>

=== midiacom/eva-robot/evaml-evasim/game-of-colors-english-eva.xml
<?xml version="1.0" encoding="UTF-8"?>
<evaml name="game-of-colors-english-eva"
	xsi:noNamespaceSchemaLocation="/home/marcelo/Dropbox/Estudo XML/EvaML-Schema/evaml_schema.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<settings>
		<voice tone="en-US_AllisonV3Voice" />
	</settings>
	<script>
		<light state="off" />
		<evaEmotion emotion="neutral" />
		<talk>Hi, I'm the robot Eva!</talk>
		<audio source="mario-game-intro" block="true" />
		<talk>Shall we play the color game?</talk>
		<evaEmotion emotion="happy" />
		<audio source="mario-start-01" block="true" />
		<talk>What's your name?</talk>
		<audio source="mario-sound1" block="true" />
			<led animation="listen" />
			<wait duration="4000" />
			<led animation="stop" />
			<wait duration="1000" />
		<talk>That Cool!</talk>
		<talk>Let's go Marcelo</talk>
		<!-- ############ Primeira cor com duas tentativas ############ -->
		<counter var="try" op="=" value="1" />
		<evaEmotion id="COR1" emotion="neutral" />
		<talk>What is this color?</talk>
		<audio source="mario-sound1" block="true" />
		<light state="on" color="blue" />
			<led animation="listen" />
		<wait duration="4000" />
		<led animation="stop" />
		<wait duration="1000" />
			<audio source="mario-start-02" block="true" />
			<talk>Very good! You're right!</talk>
		<evaEmotion emotion="happy" />
		<light state="off" />
		<wait duration="1000" />
		<!-- ############ Segunda cor com duas tentativas ############ -->
		<counter var="try" op="=" value="1" />
		<evaEmotion id="COR2" emotion="neutral" />
		<talk>What is this color?</talk>
		<audio source="mario-sound1" block="true" />
		<light state="on" color="red" />
			<led animation="listen" />
			<wait duration="4000" />
			<led animation="stop" />
			<wait duration="1000" />
				<audio source="mario-start-02" block="true" />
				<talk>Excelent! You're right!</talk>
		<evaEmotion emotion="happy" />
		<light state="off" />
		<wait duration="1000" />
		<!-- ############ Terceira cor com duas tentativas ############ -->
		<counter var="try" op="=" value="1" />
		<evaEmotion id="COR3" emotion="neutral" />
		<talk>What is this color?</talk>
		<audio source="mario-sound1" block="true" />
		<light state="on" color="green" />
			<led animation="listen" />
			<wait duration="4000" />
			<led animation="stop" />
			<wait duration="1000" />
				<audio source="mario-sound1" block="true" />
				<talk>This color is green</talk>
						<wait duration="2000" />
						<talk>Let's try one more time</talk>
						<light state="off" />
						<wait duration="2000" />
					<talk>What is this color?</talk>
					<audio source="mario-sound1" block="true" />
					<light state="on" color="green" />
						<led animation="listen" />
						<wait duration="4000" />
						<led animation="stop" />
						<wait duration="1000" />
						<audio source="mario-start-02" block="true" />
						<talk>Nice! You're correct!</talk>
		<evaEmotion emotion="happy" />
		<talk>It was really nice to play with you Marcelo</talk>
		<audio source="mario-end-02" block="true" />
		<light state="off" />
	</script>
</evaml>

=== midiacom/eva-robot/EvaML-EvaSIM source code/Windows Version/_macros.xml
<evaml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="teste4" xsi:noNamespaceSchemaLocation="EvaML-Schema/evaml_schema.xsd">
  <settings>
      <voice tone="en-US_AllisonV3Voice" />
      <lightEffects mode="OFF" />
      <audioEffects mode="ON" />
    </settings>
    <script>
      <light state="ON" color="RED" />
      <wait duration="1000" />
      <light state="ON" color="BLACK" />
      <wait duration="1000" />
      <light state="ON" color="BLUE" />
      <wait duration="1000" />
      <light state="ON" color="GREEN" />
      <wait duration="1000" />
      <light state="ON" color="PINK" />
      <wait duration="1000" />
      <light state="ON" color="WHITE" />
      <wait duration="1000" />
      <light state="ON" color="YELLOW" />
      <wait duration="1000" />
    </script>
</evaml>

=== midiacom/eva-robot/EvaML-EvaSIM source code/Linux Version/task_portugues.xml
<?xml version="1.0" encoding="UTF-8"?>
<evaml name="task_portugues"
  xsi:noNamespaceSchemaLocation="EvaML-Schema/evaml_schema.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <settings>
      <voice tone="pt-BR_IsabelaV3Voice" />
      <lightEffects mode="ON" />
      <audioEffects mode="ON" />
    </settings>
    <script>
      <!-- tarefa (parte 01) *********************************************************************** -->
      <evaEmotion emotion="NEUTRAL" />
      <light state="ON" color="WHITE" />
      <audio source="mario-start-01" block="TRUE" />
      <light state="ON" color="YELLOW" />
      <evaEmotion emotion="HAPPY" />
      <talk>Oi, eu sou o robô EVA / Olá, meu nome é EVA / Oi, como vai? Eu sou o robô EVA</talk>
      <light state="ON" color="PINK" />
      <evaEmotion emotion="NEUTRAL" />
      <wait duration="2000" />
      <!-- tarefa (parte 02) ************************************************************************* -->
      <talk>Qual o seu nome?</talk>
      <listen />
      <talk>Oi $, eu vou te mostrar minhas expressões</talk>
      <evaEmotion emotion="HAPPY"/>
      <talk>Eu posso expressar alegria</talk>
      <evaEmotion emotion="SAD"/>
      <talk>Eu posso expressar tristeza</talk> 
      <evaEmotion emotion="ANGRY"/>
      <talk>eu também posso expressar raiva</talk>
      <evaEmotion emotion="NEUTRAL"/>
      <talk>Ei $, vamos jogar o jogo da imitação? Sim ou Não?</talk>
      <listen />
      <switch var="$">
        <case op="contain" value="s"> <!-- Captura Sim-->
          <evaEmotion emotion="HAPPY" />
          <talk>Excelente! Vamos começar agora!</talk>
        </case>
        <case op="contain" value="k"> <!-- Captura Ok-->
          <evaEmotion emotion="HAPPY" />
          <talk>Excelente! Vamos começar agora!</talk>
        </case>
        <default> <!-- Captura algo diferente de sim ou ok-->
          <evaEmotion emotion="SAD" />
          <talk>Puxa, eu lamento que você não queira jogar. Adeus!</talk>
          <light state="OFF" />
          <stop />
        </default>
      </switch>
      <!-- tarefa (parte 03) ************************************************************************* -->
      <talk>Eu vou te mostrar algumas expressões e você tenta me imitar</talk>
      <counter var="score" op="=" value="0" />
      <counter var="chance" op="=" value="0" />
      <random id = "LOOP" min="1" max="3" />
      <switch var="$">
        <case op="eq" value="1">
          <evaEmotion emotion="SAD" />
          <light state="ON" color="BLUE" />
          <useMacro macro="GET_EXPRESSION" />
          <switch var="$">
            <case op="exact" value="sad">
              <useMacro macro="RIGHT_ANSWER" />
            </case>
            <default>
              <useMacro macro="WRONG_ANSWER" />
            </default>
          </switch>
        </case>
        <case op="eq" value="2">
          <evaEmotion emotion="HAPPY" />
          <light state="ON" color="YELLOW" />
          <useMacro macro="GET_EXPRESSION" />
          <switch var="$">
            <case op="exact" value="happy">
              <useMacro macro="RIGHT_ANSWER" />
            </case>
            <default>
              <useMacro macro="WRONG_ANSWER" />
            </default>
          </switch>
        </case>
        <case op="eq" value="3">
          <evaEmotion emotion="ANGRY" />
          <light state="ON" color="RED" />
          <useMacro macro="GET_EXPRESSION" />
          <switch var="$">
            <case op="exact" value="angry">
              <useMacro macro="RIGHT_ANSWER" />
            </case>
            <default>
              <useMacro macro="WRONG_ANSWER" />
            </default>
          </switch>
        </case>
      </switch>
      <counter var="chance" op="+" value="1" />
      <switch var="chance">
        <case op="eq" value="3">
          <evaEmotion emotion="HAPPY" />
          <talk>Sua pontuação foi #score</talk>
          <talk>Foi muito bom jogar com você $1. Até logo</talk>
          <light state="OFF" />
          <stop />
        </case>
        <default>
          <goto target="LOOP" />
        </default>
      </switch>
  </script>
  <macros>
    <!-- Usada na tarefa 3 -->
    <macro id="GET_EXPRESSION">
      <talk>Você consegue me imitar?</talk>
      <userEmotion />
    </macro>
    <!-- Usada na tarefa 3 -->
    <macro id="RIGHT_ANSWER">
      <evaEmotion emotion="HAPPY" />
      <talk>Muito bom! Você acertou</talk>
      <counter var="score" op="+" value="1" />
    </macro>
    <!-- Usada na tarefa 3 -->
    <macro id="WRONG_ANSWER">
      <evaEmotion emotion="SAD" />
      <talk>Puxa, não foi dessa vez!</talk>
    </macro>
  </macros>
</evaml>

=== midiacom/eva-robot/EvaML-EvaSIM-source-code BKP 12-11-23/Version1.0/tabuada_nova.xml
<?xml version="1.0" encoding="UTF-8"?>
<evaml
  name="tabuada_nova"
  xsi:noNamespaceSchemaLocation="EvaML-Schema/evaml_schema.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <settings>
    <voice tone="pt-BR_IsabelaV3Voice" />
    <lightEffects mode="ON" />
    <audioEffects mode="ON" />
  </settings>
  <script>
    <counter var="pont_min" op="=" value="3" />
    <counter var="ITERATION_VAR1" op="=" value="1"/>
    <switch id="LOOP_ID1_ITERATION_VAR1" var="ITERATION_VAR1">
      <case op="lte" value="2">
        <talk>oi</talk>
        <counter var="ITERATION_VAR1" op="+" value="1" />
        <goto target="LOOP_ID1_ITERATION_VAR1" />
      </case>
      <default>
        <light state="ON" color="YELLOW" />
      </default>
    </switch>
    <switch var="#pont_min">
      <case op="lt" value="2">
        <talk>menor que dois</talk>
      </case>
      <case op="eq" value="2">
        <talk>maior ou igual a dois</talk>
      </case>
    </switch>
    <led animation="HAPPY" />
  </script>
</evaml>
