=== midiacom/eva-robot/EvaML-EvaSIM source code/Linux Version/EvaML-Schema/evaml_schema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!-- ********************** Data type definitions ********************** -->
	<xs:simpleType name="idType">
		<xs:restriction base="xs:ID"/>
	</xs:simpleType>

	<xs:simpleType name="modeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="on"/>
			<xs:enumeration value="off"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="voiceListType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="pt-BR_IsabelaV3Voice"/>
			<xs:enumeration value="en-US_AllisonV3Voice"/>
			<xs:enumeration value="en-US_EmilyV3Voice"/>
			<xs:enumeration value="en-US_HenryV3Voice"/>
			<xs:enumeration value="es-LA_SofiaV3Voice"/>
			<xs:enumeration value="es-ES_EnriqueV3Voice"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="voiceStringType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>

	<xs:simpleType name="voiceType">
		<xs:union memberTypes="voiceListType voiceStringType" />
	</xs:simpleType>

	<xs:simpleType name="audioListType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="applause-moderate"/>
			<xs:enumeration value="beep-09"/>
			<xs:enumeration value="cheering"/>
			<xs:enumeration value="fanfare2"/>
			<xs:enumeration value="laugh-01"/>
			<xs:enumeration value="mario-end-01"/>
			<xs:enumeration value="mario-end-02"/>
			<xs:enumeration value="mario-end-03"/>
			<xs:enumeration value="mario-fundo"/>
			<xs:enumeration value="mario-game-intro"/>
			<xs:enumeration value="mario-sound1"/>
			<xs:enumeration value="mario-sound2"/>
			<xs:enumeration value="mario-start-01"/>
			<xs:enumeration value="mario-start-02"/>
			<xs:enumeration value="oh-no"/>
			<xs:enumeration value="song-exodus"/>
			<xs:enumeration value="song-the-girl-from-ipanema"/>
			<xs:enumeration value="song-the-imperial-march"/>
			<xs:enumeration value="song-vivaldi-spring"/>
			<xs:enumeration value="song-exodus"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="audioStringType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>

	<xs:simpleType name="audioFileType">
		<xs:union memberTypes="audioListType audioStringType" />
	</xs:simpleType>

	<xs:simpleType name="caseOpType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="exact"/>
			<xs:enumeration value="contain"/>
			<xs:enumeration value="eq"/>
			<xs:enumeration value="lt"/>
			<xs:enumeration value="gt"/>
			<xs:enumeration value="lte"/>
			<xs:enumeration value="gte"/>
			<xs:enumeration value="ne"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="audioBlockType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="true"/>
			<xs:enumeration value="false"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="ledAnimationType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="happy"/>
			<xs:enumeration value="sad"/>
			<xs:enumeration value="angry"/>
			<xs:enumeration value="stop"/>
			<xs:enumeration value="speak"/>
			<xs:enumeration value="listen"/>
			<xs:enumeration value="surprise"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="lightStateType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="on"/>
			<xs:enumeration value="off"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="lightRgbColorType">
		<xs:restriction base="xs:token">
			<xs:pattern value="#[\dA-F | a-f ]{6}([\dA-F | a-f][\dA-F | a-f])?"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="lightListColorType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="white"/>
			<xs:enumeration value="black"/>
			<xs:enumeration value="red"/>
			<xs:enumeration value="pink"/>
			<xs:enumeration value="green"/>
			<xs:enumeration value="yellow"/>
			<xs:enumeration value="blue"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="lightColorType">
		<xs:union memberTypes="lightListColorType lightRgbColorType" />
	</xs:simpleType>

	<xs:simpleType name="counterOpType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="="/>
			<xs:enumeration value="+"/>
			<xs:enumeration value="*"/>
			<xs:enumeration value="/"/>
			<xs:enumeration value="%"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="evaEmotionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="neutral"/>
			<xs:enumeration value="happy"/>
			<xs:enumeration value="sad"/>
			<xs:enumeration value="angry"/>
		</xs:restriction>
	</xs:simpleType>

  <!-- ********************** EvaML Commands Definitions ********************** -->
	<xs:element name="random">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="min" type="xs:nonNegativeInteger" use="required"/>
			<xs:attribute name="max" type="xs:nonNegativeInteger" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="wait">
	  <xs:complexType>
		<xs:attribute name="id" type="idType"/>
	    <xs:attribute name="duration" type="xs:nonNegativeInteger" use="required"/>
	  </xs:complexType>
	</xs:element>

	<xs:element name="talk">
		<xs:complexType mixed="true">
			<xs:attribute name="id" type="idType"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="stop">
		<xs:complexType>
		</xs:complexType>
	</xs:element>

	<xs:element name="light">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="state" type="lightStateType" use="required"/>
			<xs:attribute name="color" type="lightColorType" default="white"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="goto">
		<xs:complexType>
			<xs:attribute name="target" type="xs:IDREF" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="userEmotion">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="evaEmotion">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="emotion" type="evaEmotionType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="useMacro">
		<xs:complexType>
			<xs:attribute name="macro" type="xs:IDREF" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="listen">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="audio">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="source" type="audioFileType" use="required"/>
			<xs:attribute name="block" type="audioBlockType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="led">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="animation" type="ledAnimationType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="counter">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="var" type="xs:string" use="required"/>
			<xs:attribute name="op" type="counterOpType" use="required"/>
			<xs:attribute name="value" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="switch">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="case" minOccurs="1" maxOccurs="unbounded" />
				<xs:element ref="default" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="var" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="voice">
		<xs:complexType>
			<xs:attribute name="tone" type="voiceType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="lightEffects">
		<xs:complexType>
			<xs:attribute name="mode" type="modeType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="audioEffects">
		<xs:complexType>
			<xs:attribute name="mode" type="modeType" use="required"/>
			<xs:attribute name="vol" type="xs:string" default="100%"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="case">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="random"/>
				<xs:element ref="wait"/>
				<xs:element ref="talk"/>
				<xs:element ref="stop"/>
				<xs:element ref="light"/>
				<xs:element ref="goto"/>
				<xs:element ref="userEmotion"/>
				<xs:element ref="evaEmotion"/>
				<xs:element ref="useMacro"/>
				<xs:element ref="listen"/>
				<xs:element ref="audio"/>
				<xs:element ref="led"/>
				<xs:element ref="counter"/>
				<xs:element ref="switch"/>
			</xs:choice>
			<xs:attribute name="op" type="caseOpType" use="required"/>
			<xs:attribute name="value" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="default">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="random"/>
				<xs:element ref="wait"/>
				<xs:element ref="talk"/>
				<xs:element ref="stop"/>
				<xs:element ref="light"/>
				<xs:element ref="goto"/>
				<xs:element ref="userEmotion"/>
				<xs:element ref="evaEmotion"/>
				<xs:element ref="useMacro"/>
				<xs:element ref="listen"/>
				<xs:element ref="audio"/>
				<xs:element ref="led"/>
				<xs:element ref="counter"/>
				<xs:element ref="switch"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="macro">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="random"/>
				<xs:element ref="wait"/>
				<xs:element ref="talk"/>
				<xs:element ref="stop"/>
				<xs:element ref="light"/>
				<xs:element ref="goto"/>
				<xs:element ref="userEmotion"/>
				<xs:element ref="evaEmotion"/>
				<xs:element ref="listen"/>
				<xs:element ref="audio"/>
				<xs:element ref="led"/>
				<xs:element ref="counter"/>
				<xs:element ref="switch"/>
			</xs:choice>
			<xs:attribute name="id" type="idType" use="required" />
		</xs:complexType>
	</xs:element>

	<!-- ********************** Root Section Definition ********************** -->
	<xs:element name="evaml">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="settings"/>
				<xs:element ref="script"/>
				<xs:element ref="macros" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<!-- ********************** Settings Section Definition ********************** -->
	<xs:element name="settings">
    <xs:complexType>
			<xs:all>
				<xs:element ref="voice" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="lightEffects" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="audioEffects" minOccurs="0" maxOccurs="1"/>
			</xs:all>
    </xs:complexType>
  </xs:element>

	<!-- ********************** Script Section Definition ********************** -->
	<xs:element name="script">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="random"/>
				<xs:element ref="wait"/>
				<xs:element ref="talk"/>
				<xs:element ref="stop"/>
				<xs:element ref="light"/>
				<xs:element ref="goto"/>
				<xs:element ref="userEmotion"/>
				<xs:element ref="evaEmotion"/>
				<xs:element ref="useMacro"/>
				<xs:element ref="listen"/>
				<xs:element ref="audio"/>
				<xs:element ref="led"/>
				<xs:element ref="counter"/>
				<xs:element ref="switch"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<!-- ********************** Macros Section Definition ********************** -->
	<xs:element name="macros">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="macro"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== midiacom/eva-robot/EvaML-EvaSIM/imitation-game-english-eva.xml
<?xml version="1.0" encoding="UTF-8"?>
<evaml name="imitation-game-english-eva"
  xsi:noNamespaceSchemaLocation="/home/marcelo/Dropbox/Estudo XML/EvaML-Schema/evaml_schema.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <settings>
      <voice tone="en-US_AllisonV3Voice" />
      <lightEffects mode="on" />
      <audioEffects mode="on" vol="100%" />
    </settings>
    <script>
      <!-- tarefa (parte 01) *********************************************************************** -->
      <evaEmotion emotion="neutral" />
      <light state="on" color="white" />
      <audio source="mario-start-01" block="true" />
      <light state="on" color="yellow" />
      <evaEmotion emotion="happy" />
      <talk>Hi, I'm the robot Eva / Hello, my name is Eva / Hi, what is up. I am the robot Eva</talk>
      <light state="on" color="pink" />
      <evaEmotion emotion="neutral" />
      <wait duration="2000" />
      <!-- tarefa (parte 02) ************************************************************************* -->
      <talk>What is your name?</talk>
        <led animation="listen" />
        <wait duration="4000" />
        <led animation="stop" />
        <wait duration="1000" />
      <talk>Hello Marcelo, I'm going to present my expressions</talk>
      <evaEmotion emotion="happy"/>
      <talk>I can express happiness</talk>
      <wait duration="1500" />
      <evaEmotion emotion="sad"/>
      <talk>I can express sadness</talk> 
      <wait duration="1500" />
      <evaEmotion emotion="angry"/>
      <talk>I can express anger</talk>
      <wait duration="1500" />
      <evaEmotion emotion="neutral"/>
      <talk>Hey Marcelo, let's play the emotions game?</talk>
        <led animation="listen" />
        <wait duration="4000" />
        <led animation="stop" />
        <wait duration="1000" />
          <evaEmotion emotion="happy" />
          <talk>Excelent! Let's go now</talk>
        
      <!-- tarefa (parte 03) ************************************************************************* -->
      <talk>I will show some emotions and you try to imitate me</talk>

          <evaEmotion emotion="angry" />
          <light state="on" color="red" />
          <useMacro macro="GET_EXPRESSION" />
          <useMacro macro="RIGHT_ANSWER" />

          <evaEmotion emotion="sad" />
          <light state="on" color="blue" />
          <useMacro macro="GET_EXPRESSION" />
          <useMacro macro="WRONG_ANSWER" />

          <evaEmotion emotion="happy" />
          <light state="on" color="yellow" />
          <useMacro macro="GET_EXPRESSION" />
          <useMacro macro="RIGHT_ANSWER" />
        
     
          <evaEmotion emotion="happy" />
          <talk>Your score was two</talk>
          <talk>It was good to play with you Marcelo. Bye</talk>
          <light state="off" />

  </script>
  <macros>
    <!-- Usada na tarefa 3 -->
    <macro id="GET_EXPRESSION">
      <talk>Can you imitate me?</talk>
      <audio source="mario-fundo" block="true" />
    </macro>
    <!-- Usada na tarefa 3 -->
    <macro id="RIGHT_ANSWER">
      <evaEmotion emotion="happy" />
      <audio source="fanfare2" block="true" />
      <talk>Ok! You are correct</talk>
    </macro>
    <!-- Usada na tarefa 3 -->
    <macro id="WRONG_ANSWER">
      <evaEmotion emotion="sad" />
      <talk>You are wrong</talk>
    </macro>
  </macros>
</evaml>

=== midiacom/eva-robot/EvaML-EvaSIM source code/Linux Version/task.xml
<?xml version="1.0" encoding="UTF-8"?>
<evaml name="task"
  xsi:noNamespaceSchemaLocation="EvaML-Schema/evaml_schema.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <settings>
      <voice tone="en-US_AllisonV3Voice" />
      <lightEffects mode="ON" />
      <audioEffects mode="ON" />
    </settings>
    <script>
      <!-- tarefa (parte 01) *********************************************************************** -->
      <evaEmotion emotion="NEUTRAL" />
      <light state="ON" color="WHITE" />
      <audio source="mario-start-01" block="TRUE" />
      <light state="ON" color="YELLOW" />
      <evaEmotion emotion="HAPPY" />
      <talk>Hi, I'm the robot Eva / Hello, my name is Eva / Hi, what is up. I am the robot Eva</talk>
      <light state="ON" color="PINK" />
      <evaEmotion emotion="NEUTRAL" />
      <wait duration="2000" />
      <!-- tarefa (parte 02) ************************************************************************* -->
      <talk>What is your name?</talk>
      <listen />
      <talk>Hello $, I'm going to present my expressions</talk>
      <evaEmotion emotion="HAPPY"/>
      <talk>I can express happiness</talk>
      <evaEmotion emotion="SAD"/>
      <talk>I can express sadness</talk> 
      <evaEmotion emotion="ANGRY"/>
      <talk>I can express anger</talk>
      <evaEmotion emotion="NEUTRAL"/>
      <talk>Hey $, let's play the emotions game?</talk>
      <listen />
      <switch var="$">
        <case op="contain" value="yes">
          <evaEmotion emotion="HAPPY" />
          <talk>Excelent! Let's go now</talk>
        </case>
        <case op="contain" value="no">
          <evaEmotion emotion="SAD" />
          <talk>Oh, I'm sorry you don't want to play. Bye!</talk>
          <light state="OFF" />
          <stop />
        </case>
      </switch>
      <!-- tarefa (parte 03) ************************************************************************* -->
      <talk>I will show some emotions and you try to imitate me</talk>
      <counter var="score" op="=" value="0" />
      <counter var="chance" op="=" value="0" />
      <random id = "LOOP" min="1" max="3" />
      <switch var="$">
        <case op="eq" value="1">
          <evaEmotion emotion="SAD" />
          <light state="ON" color="BLUE" />
          <useMacro macro="GET_EXPRESSION" />
          <switch var="$">
            <case op="exact" value="sad">
              <useMacro macro="RIGHT_ANSWER" />
            </case>
            <default>
              <useMacro macro="WRONG_ANSWER" />
            </default>
          </switch>
        </case>
        <case op="eq" value="2">
          <evaEmotion emotion="HAPPY" />
          <light state="ON" color="YELLOW" />
          <useMacro macro="GET_EXPRESSION" />
          <switch var="$">
            <case op="exact" value="happy">
              <useMacro macro="RIGHT_ANSWER" />
            </case>
            <default>
              <useMacro macro="WRONG_ANSWER" />
            </default>
          </switch>
        </case>
        <case op="eq" value="3">
          <evaEmotion emotion="ANGRY" />
          <light state="ON" color="RED" />
          <useMacro macro="GET_EXPRESSION" />
          <switch var="$">
            <case op="exact" value="angry">
              <useMacro macro="RIGHT_ANSWER" />
            </case>
            <default>
              <useMacro macro="WRONG_ANSWER" />
            </default>
          </switch>
        </case>
      </switch>
      <counter var="chance" op="+" value="1" />
      <switch var="chance">
        <case op="eq" value="3">
          <evaEmotion emotion="HAPPY" />
          <talk>Your score was #score</talk>
          <talk>It was good to play with you $1. Bye</talk>
          <light state="OFF" />
          <stop />
        </case>
        <default>
          <goto target="LOOP" />
        </default>
      </switch>
  </script>
  <macros>
    <!-- Usada na tarefa 3 -->
    <macro id="GET_EXPRESSION">
      <talk>Can you imitate me?</talk>
      <userEmotion />
    </macro>
    <!-- Usada na tarefa 3 -->
    <macro id="RIGHT_ANSWER">
      <evaEmotion emotion="HAPPY" />
      <talk>Ok! You are correct</talk>
      <counter var="score" op="+" value="1" />
    </macro>
    <!-- Usada na tarefa 3 -->
    <macro id="WRONG_ANSWER">
      <evaEmotion emotion="SAD" />
      <talk>You are wrong</talk>
    </macro>
  </macros>
</evaml>

=== midiacom/eva-robot/EvaML-EvaSIM-source-code BKP 12-11-23/Version1.0/_node_keys.xml
<evaml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="evaml-task-completed" xsi:noNamespaceSchemaLocation="EvaML-Schema/evaml_schema.xsd" id="176b9d05ee26889ec54d0105af2148b9">
  <settings>
    <voice tone="en-US_AllisonV3Voice" key="1000" />
    <lightEffects mode="ON" />
    <audioEffects mode="ON" />
  </settings>
  <script>
    
    <evaEmotion emotion="NEUTRAL" key="1001" />
    <light state="ON" color="WHITE" key="1002" />
    <audio source="mario-game-intro" block="TRUE" key="1003" />
    <light state="ON" color="YELLOW" key="1004" />
    <evaEmotion emotion="HAPPY" key="1005" />
    <talk key="1006">Hi, I'm the robot EVA / Hello, my name is EVA / Hi, what is up. I am the robot EVA</talk>
    <light state="ON" color="PINK" key="1007" />
    <evaEmotion emotion="NEUTRAL" key="1008" />
    <wait duration="2000" key="1009" />
    
    <talk key="1010">What is your name?</talk>
    <listen key="1011" />
    <talk key="1012">Hello $. I'm going to present my expressions</talk>
    <evaEmotion emotion="HAPPY" key="1013" />
    <talk key="1014">I can express hapiness</talk>
    <evaEmotion emotion="SAD" key="1015" />
    <talk key="1016">I can express sadness</talk>
    <evaEmotion emotion="ANGRY" key="1017" />
    <talk key="1018">I can express anger</talk>
    <evaEmotion emotion="NEUTRAL" key="1019" />
    <talk key="1020">Hey $, let's play the emotions game?</talk>
    <listen key="1021" />
    <switch var="$">
      <case op="exact" value="yes" key="1022" child_proc="false">
        <evaEmotion emotion="HAPPY" key="1023" />
        <talk key="1024">Excelent! Let's go now!</talk>
      </case>
      <case op="exact" value="no" key="1025" child_proc="false">
        <evaEmotion emotion="SAD" key="1026" />
        <talk key="1027">Oh, I'm sorry you don't want to play. Bye!</talk>
        <light state="OFF" key="1028" />
        <stop />        
      </case>
    <default key="1029" child_proc="false" /></switch>
    
    <talk key="1030">I will show some emotions and you try to imitate me</talk>
    <counter var="score" op="=" value="0" key="1031" />
    <counter var="chance" op="=" value="0" key="1032" />
    <random id="LOOP" min="1" max="3" key="1033" />
    <switch var="$">
      <case op="exact" value="1" key="1034" child_proc="false">
        <evaEmotion emotion="SAD" key="1035" />
        <light state="ON" color="BLUE" key="1036" />
        <talk key="1037">Can you imitate me?</talk>
      <userEmotion key="1038" />
      <audio source="mario-start-01" block="TRUE" key="1039" />
    <switch var="$">
          <case op="exact" value="sad" key="1040" child_proc="false">
            <evaEmotion emotion="HAPPY" key="1041" />
      <audio source="trumpets" block="TRUE" key="1042" />
      <talk key="1043">Ok! You are correct!</talk>
      <counter var="score" op="+" value="1" key="1044" />
    </case>
          <default key="1045" child_proc="false">
            <evaEmotion emotion="SAD" key="1046" />
      <talk key="1047">You are wrong!</talk>
    </default>
        </switch>
      </case>
      <case op="exact" value="2" key="1048" child_proc="false">
        <evaEmotion emotion="HAPPY" key="1049" />
        <light state="ON" color="YELLOW" key="1050" />
        <talk key="1051">Can you imitate me?</talk>
      <userEmotion key="1052" />
      <audio source="mario-start-01" block="TRUE" key="1053" />
    <switch var="$">
          <case op="exact" value="happy" key="1054" child_proc="false">
            <evaEmotion emotion="HAPPY" key="1055" />
      <audio source="trumpets" block="TRUE" key="1056" />
      <talk key="1057">Ok! You are correct!</talk>
      <counter var="score" op="+" value="1" key="1058" />
    </case>
          <default key="1059" child_proc="false">
            <evaEmotion emotion="SAD" key="1060" />
      <talk key="1061">You are wrong!</talk>
    </default>
        </switch>
      </case>
      <case op="exact" value="3" key="1062" child_proc="false">
        <evaEmotion emotion="ANGRY" key="1063" />
        <light state="ON" color="RED" key="1064" />
        <talk key="1065">Can you imitate me?</talk>
      <userEmotion key="1066" />
      <audio source="mario-start-01" block="TRUE" key="1067" />
    <switch var="$">
          <case op="exact" value="angry" key="1068" child_proc="false">
            <evaEmotion emotion="HAPPY" key="1069" />
      <audio source="trumpets" block="TRUE" key="1070" />
      <talk key="1071">Ok! You are correct!</talk>
      <counter var="score" op="+" value="1" key="1072" />
    </case>
          <default key="1073" child_proc="false">
            <evaEmotion emotion="SAD" key="1074" />
      <talk key="1075">You are wrong!</talk>
    </default>
        </switch>
      </case>
    <default key="1076" child_proc="false" /></switch>
    <counter var="chance" op="+" value="1" key="1077" />
    <switch var="chance">
      <case op="eq" value="3" key="1078" child_proc="false">
        <evaEmotion emotion="HAPPY" key="1079" />
        <talk key="1080">Your score was #score</talk>
        <talk key="1081">It was good to play with you $1. Bye!</talk>
      </case>
      <default key="1082" child_proc="false">
        <goto target="LOOP" />
      </default>
    </switch>
  </script>
  
  </evaml>
