=== midiacom/eva-robot/EvaML-EvaSIM-source-code/Version1.0/EvaML-Schema/evaml_schema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<!--
XML Schema for the EvaML Language
This is EvaML
Copyright : 2022 LABORATORIO MIDIACOM, All Rights Reserved.
See https://www.midiacom.uff.br
PublicURI : https://github.com/midiacom/eva-robot/blob/master/EvaML-EvaSIM-source-code/Linux%20Version/EvaML-Schema/evaml_schema.xsd
Author : Marcelo Marques da Rocha
Revision: 2022/08/12
-->
  <!-- ** Data type definitions ** -->
	<xs:simpleType name="idType">
		<xs:restriction base="xs:ID"/>
	</xs:simpleType>

	<xs:simpleType name="modeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ON"/>
			<xs:enumeration value="OFF"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="voiceListType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="pt-BR_IsabelaV3Voice"/>
			<xs:enumeration value="en-US_AllisonV3Voice"/> 
			<xs:enumeration value="en-US_AllisonExpressive"/> 
			<xs:enumeration value="en-US_EmmaExpressive"/>
			<xs:enumeration value="en-US_LisaExpressive"/>
			<xs:enumeration value="en-US_MichaelExpressive"/>
			<xs:enumeration value="en-US_MichaelV3Voice"/>
			<xs:enumeration value="en-US_KevinV3Voice"/>
			<xs:enumeration value="en-US_OliviaV3Voice"/>
			<xs:enumeration value="en-US_EmilyV3Voice"/>
			<xs:enumeration value="en-US_HenryV3Voice"/>
			<xs:enumeration value="es-LA_SofiaV3Voice"/>
			<xs:enumeration value="es-ES_LauraV3Voice"/>
			<xs:enumeration value="es-ES_EnriqueV3Voice"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="motionListType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="YES"/>
			<xs:enumeration value="NO"/>
			<xs:enumeration value="CENTER"/>
			<xs:enumeration value="LEFT"/>
			<xs:enumeration value="RIGHT"/>
			<xs:enumeration value="UP"/>
			<xs:enumeration value="DOWN"/>
			<xs:enumeration value="2UP"/>
			<xs:enumeration value="2DOWN"/>
			<xs:enumeration value="2RIGHT"/>
			<xs:enumeration value="2LEFT"/>
			<xs:enumeration value="DOWN_RIGHT"/>
			<xs:enumeration value="2DOWN_RIGHT"/>
			<xs:enumeration value="DOWN_LEFT"/>
			<xs:enumeration value="2DOWN_LEFT"/>
			<xs:enumeration value="UP_RIGHT"/>
			<xs:enumeration value="2UP_RIGHT"/>
			<xs:enumeration value="UP_LEFT"/>
			<xs:enumeration value="2UP_LEFT"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="voiceStringType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>

	<xs:simpleType name="voiceType">
		<xs:union memberTypes="voiceListType voiceStringType" />
	</xs:simpleType>

	<xs:simpleType name="topicType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>

	<xs:simpleType name="messageType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>

	<xs:simpleType name="audioListType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="efx-blin"/>
            <xs:enumeration value="efx-cheering"/>
            <xs:enumeration value="efx-crowdapplause1"/>
            <xs:enumeration value="efx-fanfare"/>
            <xs:enumeration value="efx-mario-end-01"/>
            <xs:enumeration value="efx-mario-end-02"/>
            <xs:enumeration value="efx-mario-end-03"/>
            <xs:enumeration value="efx-mario-fundo"/>
            <xs:enumeration value="efx-mario-game-intro"/>
            <xs:enumeration value="efx-mario-sound1-longo"/>
            <xs:enumeration value="efx-mario-sound1"/>
            <xs:enumeration value="efx-mario-sound2"/>
            <xs:enumeration value="efx-mario-start-01"/>
            <xs:enumeration value="efx-mario-start-02"/>
            <xs:enumeration value="efx-tic-toc"/>
            <xs:enumeration value="efx-wand1"/>
            <xs:enumeration value="MUTED-SOUND"/>
            <xs:enumeration value="song-ben"/>
            <xs:enumeration value="song-caneta-azul"/>
            <xs:enumeration value="song-exodus"/>
            <xs:enumeration value="song-mj-heal-the-world"/>
            <xs:enumeration value="song-here-comes-the-sun"/>
            <xs:enumeration value="song-mj-heal-the-world"/>
            <xs:enumeration value="song-mj-thriller2"/>
            <xs:enumeration value="song-mj-thriller3-laugh"/>
            <xs:enumeration value="song-oh-no"/>
            <xs:enumeration value="song-take-on-me"/>
            <xs:enumeration value="song-the-girl-from-ipanema"/>
            <xs:enumeration value="song-the-imperial-march"/>
            <xs:enumeration value="song-thriller-open"/>
            <xs:enumeration value="song-vivaldi-spring"/>
            <xs:enumeration value="song-weird-science"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="audioStringType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>

	<xs:simpleType name="audioFileType">
		<xs:union memberTypes="audioListType audioStringType" />
	</xs:simpleType>

	<xs:simpleType name="caseOpType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="exact"/>
			<xs:enumeration value="contain"/>
			<xs:enumeration value="eq"/>
			<xs:enumeration value="lt"/>
			<xs:enumeration value="gt"/>
			<xs:enumeration value="lte"/>
			<xs:enumeration value="gte"/>
			<xs:enumeration value="ne"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="audioBlockType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="TRUE"/>
			<xs:enumeration value="FALSE"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="ledAnimationType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="HAPPY"/>
			<xs:enumeration value="SAD"/>
			<xs:enumeration value="ANGRY"/>
            <xs:enumeration value="ANGRY2"/>
			<xs:enumeration value="STOP"/>
			<xs:enumeration value="SPEAK"/>
			<xs:enumeration value="LISTEN"/>
			<xs:enumeration value="SURPRISE"/>
            <xs:enumeration value="WHITE"/>
            <xs:enumeration value="RAINBOW"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="lightStateType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ON"/>
			<xs:enumeration value="OFF"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="lightRgbColorType">
		<xs:restriction base="xs:token">
			<xs:pattern value="#[\dA-F | a-f ]{6}([\dA-F | a-f][\dA-F | a-f])?"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="lightListColorType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="WHITE"/>
			<xs:enumeration value="BLACK"/>
			<xs:enumeration value="RED"/>
			<xs:enumeration value="PINK"/>
			<xs:enumeration value="GREEN"/>
			<xs:enumeration value="YELLOW"/>
			<xs:enumeration value="BLUE"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="lightColorType">
		<xs:union memberTypes="lightListColorType lightRgbColorType" />
	</xs:simpleType>

	<xs:simpleType name="counterOpType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="="/>
			<xs:enumeration value="+"/>
			<xs:enumeration value="*"/>
			<xs:enumeration value="/"/>
			<xs:enumeration value="%"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="evaEmotionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="NEUTRAL"/>
			<xs:enumeration value="HAPPY"/>
			<xs:enumeration value="SAD"/>
			<xs:enumeration value="ANGRY"/>
			<xs:enumeration value="FEAR"/>
			<xs:enumeration value="SURPRISE"/>
			<xs:enumeration value="INLOVE"/>
		</xs:restriction>
	</xs:simpleType>

  <!-- ** EvaML Commands Definitions ** -->

  <xs:element name="mqtt">
	<xs:complexType>
		<xs:attribute name="topic" type="topicType" use="required"/>
		<xs:attribute name="message" type="messageType" use="required"/>
	</xs:complexType>
</xs:element>

	<xs:element name="random">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="min" type="xs:nonNegativeInteger" use="required"/>
			<xs:attribute name="max" type="xs:nonNegativeInteger" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="wait">
	  <xs:complexType>
		<xs:attribute name="id" type="idType"/>
	    <xs:attribute name="duration" type="xs:nonNegativeInteger" use="required"/>
	  </xs:complexType>
	</xs:element>

	<xs:element name="talk">
		<xs:complexType mixed="true">
			<xs:attribute name="id" type="idType"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="stop">
		<xs:complexType>
		</xs:complexType>
	</xs:element>

	<xs:element name="light">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="state" type="lightStateType" use="required"/>
			<xs:attribute name="color" type="lightColorType" default="WHITE"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="goto">
		<xs:complexType>
			<xs:attribute name="target" type="xs:IDREF" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="userEmotion">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="evaEmotion">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="emotion" type="evaEmotionType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="useMacro">
		<xs:complexType>
			<xs:attribute name="macro" type="xs:IDREF" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="listen">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="audio">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="source" type="audioFileType" use="required"/>
			<xs:attribute name="block" type="audioBlockType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="led">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="animation" type="ledAnimationType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="counter">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="var" type="xs:string" use="required"/>
			<xs:attribute name="op" type="counterOpType" use="required"/>
			<xs:attribute name="value" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="switch">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="case" minOccurs="1" maxOccurs="unbounded" />
				<xs:element ref="default" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="var" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="motion">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="type" type="motionListType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="voice">
		<xs:complexType>
			<xs:attribute name="tone" type="voiceType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="lightEffects">
		<xs:complexType>
			<xs:attribute name="mode" type="modeType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="audioEffects">
		<xs:complexType>
			<xs:attribute name="mode" type="modeType" use="required"/>
			<xs:attribute name="vol" type="xs:string" default="100%"/>
		</xs:complexType>
	</xs:element>
    
	<xs:element name="loop">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="loop"/>
				<xs:element ref="mqtt"/>
				<xs:element ref="random"/>
				<xs:element ref="wait"/>
				<xs:element ref="talk"/>
				<xs:element ref="stop"/>
				<xs:element ref="light"/>
				<xs:element ref="goto"/>
				<xs:element ref="motion"/>
				<xs:element ref="userEmotion"/>
				<xs:element ref="evaEmotion"/>
				<xs:element ref="useMacro"/>
				<xs:element ref="listen"/>
				<xs:element ref="audio"/>
				<xs:element ref="led"/>
				<xs:element ref="counter"/>
				<xs:element ref="switch"/>
			</xs:choice>
			<xs:attribute name="id" type="idType"/>
		    <xs:attribute name="var" type="xs:string" use="optional"/>
		    <xs:attribute name="times" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="case">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="loop"/>
				<xs:element ref="mqtt"/>
				<xs:element ref="random"/>
				<xs:element ref="wait"/>
				<xs:element ref="talk"/>
				<xs:element ref="stop"/>
				<xs:element ref="light"/>
				<xs:element ref="goto"/>
				<xs:element ref="motion"/>
				<xs:element ref="userEmotion"/>
				<xs:element ref="evaEmotion"/>
				<xs:element ref="useMacro"/>
				<xs:element ref="listen"/>
				<xs:element ref="audio"/>
				<xs:element ref="led"/>
				<xs:element ref="counter"/>
				<xs:element ref="switch"/>
			</xs:choice>
			<xs:attribute name="op" type="caseOpType" use="required"/>
			<xs:attribute name="value" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="default">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="loop"/>
				<xs:element ref="mqtt"/>
				<xs:element ref="random"/>
				<xs:element ref="wait"/>
				<xs:element ref="talk"/>
				<xs:element ref="stop"/>
				<xs:element ref="light"/>
				<xs:element ref="goto"/>
				<xs:element ref="motion"/>
				<xs:element ref="userEmotion"/>
				<xs:element ref="evaEmotion"/>
				<xs:element ref="useMacro"/>
				<xs:element ref="listen"/>
				<xs:element ref="audio"/>
				<xs:element ref="led"/>
				<xs:element ref="counter"/>
				<xs:element ref="switch"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="macro">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="loop"/>
				<xs:element ref="mqtt"/>
				<xs:element ref="random"/>
				<xs:element ref="wait"/>
				<xs:element ref="talk"/>
				<xs:element ref="stop"/>
				<xs:element ref="light"/>
				<xs:element ref="goto"/>
				<xs:element ref="motion"/>
				<xs:element ref="userEmotion"/>
				<xs:element ref="evaEmotion"/>
				<xs:element ref="listen"/>
				<xs:element ref="audio"/>
				<xs:element ref="led"/>
				<xs:element ref="counter"/>
				<xs:element ref="switch"/>
			</xs:choice>
			<xs:attribute name="id" type="idType" use="required" />
		</xs:complexType>
	</xs:element>

	<!-- ** Root Section Definition ** -->
	<xs:element name="evaml">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="settings"/>
				<xs:element ref="script"/>
				<xs:element ref="macros" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<!-- ** Settings Section Definition ** -->
	<xs:element name="settings">
    <xs:complexType>
			<xs:all>
				<xs:element ref="voice" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="lightEffects" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="audioEffects" minOccurs="0" maxOccurs="1"/>
			</xs:all>
    </xs:complexType>
  </xs:element>

	<!-- ** Script Section Definition ** -->
	<xs:element name="script">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="loop"/>
				<xs:element ref="mqtt"/>
				<xs:element ref="random"/>
				<xs:element ref="wait"/>
				<xs:element ref="talk"/>
				<xs:element ref="stop"/>
				<xs:element ref="light"/>
				<xs:element ref="goto"/>
				<xs:element ref="motion"/>
				<xs:element ref="userEmotion"/>
				<xs:element ref="evaEmotion"/>
				<xs:element ref="useMacro"/>
				<xs:element ref="listen"/>
				<xs:element ref="audio"/>
				<xs:element ref="led"/>
				<xs:element ref="counter"/>
				<xs:element ref="switch"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<!-- ** Macros Section Definition ** -->
	<xs:element name="macros">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="macro"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== midiacom/eva-robot/EvaML-EvaSIM-source-code/Version1.0/my_script_file.xml
<evaml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Teste_Renan" xsi:noNamespaceSchemaLocation="EvaML-Schema/evaml_schema.xsd">
  <settings>
    <voice tone="pt-BR_IsabelaV3Voice"/>
    <lightEffects mode="ON"/>
    <audioEffects mode="ON"/>
  </settings>
  <script>
    <evaEmotion emotion="NEUTRAL"/> 
    <light state="ON" color="WHITE"/>
    <audio source="mario-end-01" block="TRUE"/>
    <light state="ON" color="YELLOW"/>
    <evaEmotion emotion="HAPPY"/>
    <talk>Olá, eu sou o robô EVA. / Olá, eu sou EVA. / Olá, eu sou um robô. </talk>
    <light state="ON" color="PINK"/>
    <evaEmotion emotion="NEUTRAL"/>
    <wait duration="2000"/>
    <talk>Qual é o seu nome?</talk>
    <listen/>
    <talk>Olá $, tudo bem com você? Irei te apresentar minhas emoções. </talk>
    <wait duration="2000"/>
    <talk>Desse modo, estou feliz.</talk>
    <evaEmotion emotion="HAPPY"/>
    <talk>Desse outro jeito, estou triste.</talk>
    <evaEmotion emotion="SAD"/>
    <talk>E desse modo, estou com raiva.</talk>
    <evaEmotion emotion="ANGRY"/>
    <evaEmotion emotion="NEUTRAL"/>
    <talk>Você gostaria de jogar o jogo da imitação comigo?</talk>
    <listen/>
    <switch var="$">
    <case op="exact" value="Sim">
    <light state="ON" color="WHITE"/>
    <evaEmotion emotion="HAPPY"/>
    <talk>Que bom que você quer jogar comigo, vamos jogar então.</talk>
    <evaEmotion emotion="NEUTRAL"/>
    <audio source="mario-start-01" block="TRUE"/>
    <talk>Para começarmos o jogo, irei primeiro te ensinar os passos.</talk>
    <talk>Eu irei te apresentar uma das três emoções de maneira aleatória, com uma cor que a acompanhe. Você deverá imitar o sentimento apresentado.</talk>
    <talk>Você está preparado?</talk>
    <light state="ON" color="WHITE"/>
    <evaEmotion emotion="NEUTRAL"/>
    <listen/>
    <switch var="$">
    <case op="exact" value="Sim">
    <counter var="ponto" op="=" value="0"/>
    <light state="ON" color="GREEN"/>
    <talk>Então vamos começar.</talk>
    <counter var="ponto" op="=" value="0"/>
    <useMacro macro="rodada"/>
    <useMacro macro="rodada"/>
    <useMacro macro="rodada"/>
    <evaEmotion emotion="HAPPY"/>
    <talk>Fico feliz em termos jogados juntos $1, sua pontuação foi de #ponto no total. Gostou da experiência? Te vejo na próxima! </talk>
    <evaEmotion emotion="NEUTRAL"/>
    <light state="ON" color="WHITE"/>
    </case>
    <case op="exact" value="Não">
    <talk>Então começaremos mais tarde.</talk>
    <stop/>
    </case>
    </switch>
    </case>
    <case op="exact" value="Não">
    <light state="ON" color="RED"/>
    <evaEmotion emotion="SAD"/>
    <talk>É uma pena não jogarmos juntos, mas espero que esteja disposto na próxima vez.</talk>
    <audio source="mario-end-03" block="TRUE"/>
    </case>
    </switch>
  </script>
  <macros>
    <macro id="rodada">
      <counter var="HAPPY" op="=" value="0"/>
      <counter var="SAD" op="=" value="0"/>
      <counter var="ANGRY" op="=" value="0"/>
      <random min="0" max="2"/>
      <switch var="$">
        <case op="exact" value="0">
          <evaEmotion emotion="HAPPY"/>
          <counter var="HAPPY" op="+" value="1"/>
          <light state="ON" color="GREEN"/>
        </case>
        <case op="exact" value="1">
          <counter var="SAD" op="+" value="1"/>
          <evaEmotion emotion="SAD"/>
          <light state="ON" color="BLUE"/>
        </case>
        <case op="exact" value="2">
          <counter var="ANGRY" op="+" value="1"/>
          <evaEmotion emotion="ANGRY"/>
          <light state="ON" color="RED"/>
        </case>
      </switch>
      <userEmotion/>
      <switch var="$">
        <case op="exact" value="HAPPY">
          <counter var="HAPPY" op="+" value="1"/>
        </case>
        <case op="exact" value="ANGRY">
          <counter var="ANGRY" op="+" value="1"/>
        </case>
        <case op="exact" value="SAD">
          <counter var="SAD" op="+" value="1"/>
        </case>
      </switch>
      <counter var="HAPPY" op="+" value="1"/>
      <switch var="HAPPY">
        <case op="gt" value="2">
          <audio source="applause-moderate" block="TRUE"/>
          <evaEmotion emotion="HAPPY"/>
          <light state="ON" color="PINK"/>
          <talk>parabéns, voce ganhou um ponto.</talk>
          <counter var="ponto" op="+" value="1"/>
          <evaEmotion emotion="NEUTRAL"/>
          <wait duration="1000"/>
        </case>
        <default>
          <counter var="ANGRY" op="+" value="1"/>
          <switch var="ANGRY">
            <case op="gt" value="2">
              <audio source="applause-moderate" block="TRUE"/>
              <evaEmotion emotion="HAPPY"/>
              <light state="ON" color="PINK"/>
              <talk>parabéns, voce ganhou um ponto.</talk>
              <counter var="ponto" op="+" value="1"/>
              <evaEmotion emotion="NEUTRAL"/>
              <wait duration="1000"/>
            </case>
            <default>
              <counter var="SAD" op="+" value="1"/>
              <switch var="SAD">
                <case op="gt" value="2">
                  <audio source="applause-moderate" block="TRUE"/>
                  <evaEmotion emotion="HAPPY"/>
                  <light state="ON" color="PINK"/>
                  <talk>parabéns, voce ganhou um ponto.</talk>
                  <counter var="ponto" op="+" value="1"/>
                  <evaEmotion emotion="NEUTRAL"/>
                  <wait duration="1000"/>
                </case>
                <default>
                  <evaEmotion emotion="SAD"/>
                  <audio source="mario-end-02" block="TRUE"/>
                  <light state="ON" color="BLACK"/>
                  <talk>é uma pena, mas nessa rodada você não acertou.</talk>
                  <evaEmotion emotion="NEUTRAL"/>
                  <wait duration="1000"/>
                </default>
              </switch>
            </default>
          </switch>
        </default>
      </switch>
    </macro>
  </macros>
</evaml>

=== midiacom/eva-robot/EvaML-EvaSIM-source-code/Version1.0/meu_teste.xml
<?xml version="1.0" encoding="UTF-8"?>
<evaml
  name="meu_teste"
  xsi:noNamespaceSchemaLocation="EvaML-Schema/evaml_schema.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <settings>
    <voice tone="pt-BR_IsabelaV3Voice" />
    <lightEffects mode="ON" />
    <audioEffects mode="ON" />
  </settings>
  <script>
    <counter var="multiplicando" op="=" value="8" />
    <talk>Quanto Ã© 1 vezes 8</talk>
    <listen />
    <switch var="$">
      <case op="eq" value="#multiplicando">
        <light state="ON" color="GREEN"/>
      </case>
      <default>
        <light state="ON" color="RED" />
      </default>
    </switch>
  </script>
</evaml>
