=== midiacom/eva-robot/EvaML-EvaSIM-source-code/Version1.0/EvaML-Schema/evaml_schema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<!--
XML Schema for the EvaML Language
This is EvaML
Copyright : 2022 LABORATORIO MIDIACOM, All Rights Reserved.
See https://www.midiacom.uff.br
PublicURI : https://github.com/midiacom/eva-robot/blob/master/EvaML-EvaSIM-source-code/Linux%20Version/EvaML-Schema/evaml_schema.xsd
Author : Marcelo Marques da Rocha
Revision: 2022/08/12
-->
  <!-- ** Data type definitions ** -->
	<xs:simpleType name="idType">
		<xs:restriction base="xs:ID"/>
	</xs:simpleType>

	<xs:simpleType name="modeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ON"/>
			<xs:enumeration value="OFF"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="voiceListType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="pt-BR_IsabelaV3Voice"/>
			<xs:enumeration value="en-US_AllisonV3Voice"/> 
			<xs:enumeration value="en-US_AllisonExpressive"/> 
			<xs:enumeration value="en-US_EmmaExpressive"/>
			<xs:enumeration value="en-US_LisaExpressive"/>
			<xs:enumeration value="en-US_MichaelExpressive"/>
			<xs:enumeration value="en-US_MichaelV3Voice"/>
			<xs:enumeration value="en-US_KevinV3Voice"/>
			<xs:enumeration value="en-US_OliviaV3Voice"/>
			<xs:enumeration value="en-US_EmilyV3Voice"/>
			<xs:enumeration value="en-US_HenryV3Voice"/>
			<xs:enumeration value="es-LA_SofiaV3Voice"/>
			<xs:enumeration value="es-ES_LauraV3Voice"/>
			<xs:enumeration value="es-ES_EnriqueV3Voice"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="motionListType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="YES"/>
			<xs:enumeration value="NO"/>
			<xs:enumeration value="CENTER"/>
			<xs:enumeration value="LEFT"/>
			<xs:enumeration value="RIGHT"/>
			<xs:enumeration value="UP"/>
			<xs:enumeration value="DOWN"/>
			<xs:enumeration value="2UP"/>
			<xs:enumeration value="2DOWN"/>
			<xs:enumeration value="2RIGHT"/>
			<xs:enumeration value="2LEFT"/>
			<xs:enumeration value="DOWN_RIGHT"/>
			<xs:enumeration value="2DOWN_RIGHT"/>
			<xs:enumeration value="DOWN_LEFT"/>
			<xs:enumeration value="2DOWN_LEFT"/>
			<xs:enumeration value="UP_RIGHT"/>
			<xs:enumeration value="2UP_RIGHT"/>
			<xs:enumeration value="UP_LEFT"/>
			<xs:enumeration value="2UP_LEFT"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="voiceStringType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>

	<xs:simpleType name="voiceType">
		<xs:union memberTypes="voiceListType voiceStringType" />
	</xs:simpleType>

	<xs:simpleType name="topicType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>

	<xs:simpleType name="messageType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>

	<xs:simpleType name="audioListType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="efx-blin"/>
            <xs:enumeration value="efx-cheering"/>
            <xs:enumeration value="efx-crowdapplause1"/>
            <xs:enumeration value="efx-fanfare"/>
            <xs:enumeration value="efx-mario-end-01"/>
            <xs:enumeration value="efx-mario-end-02"/>
            <xs:enumeration value="efx-mario-end-03"/>
            <xs:enumeration value="efx-mario-fundo"/>
            <xs:enumeration value="efx-mario-game-intro"/>
            <xs:enumeration value="efx-mario-sound1-longo"/>
            <xs:enumeration value="efx-mario-sound1"/>
            <xs:enumeration value="efx-mario-sound2"/>
            <xs:enumeration value="efx-mario-start-01"/>
            <xs:enumeration value="efx-mario-start-02"/>
            <xs:enumeration value="efx-tic-toc"/>
            <xs:enumeration value="efx-wand1"/>
            <xs:enumeration value="MUTED-SOUND"/>
            <xs:enumeration value="song-ben"/>
            <xs:enumeration value="song-caneta-azul"/>
            <xs:enumeration value="song-exodus"/>
            <xs:enumeration value="song-mj-heal-the-world"/>
            <xs:enumeration value="song-here-comes-the-sun"/>
            <xs:enumeration value="song-mj-heal-the-world"/>
            <xs:enumeration value="song-mj-thriller2"/>
            <xs:enumeration value="song-mj-thriller3-laugh"/>
            <xs:enumeration value="song-oh-no"/>
            <xs:enumeration value="song-take-on-me"/>
            <xs:enumeration value="song-the-girl-from-ipanema"/>
            <xs:enumeration value="song-the-imperial-march"/>
            <xs:enumeration value="song-thriller-open"/>
            <xs:enumeration value="song-vivaldi-spring"/>
            <xs:enumeration value="song-weird-science"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="audioStringType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>

	<xs:simpleType name="audioFileType">
		<xs:union memberTypes="audioListType audioStringType" />
	</xs:simpleType>

	<xs:simpleType name="caseOpType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="exact"/>
			<xs:enumeration value="contain"/>
			<xs:enumeration value="eq"/>
			<xs:enumeration value="lt"/>
			<xs:enumeration value="gt"/>
			<xs:enumeration value="lte"/>
			<xs:enumeration value="gte"/>
			<xs:enumeration value="ne"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="audioBlockType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="TRUE"/>
			<xs:enumeration value="FALSE"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="ledAnimationType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="HAPPY"/>
			<xs:enumeration value="SAD"/>
			<xs:enumeration value="ANGRY"/>
            <xs:enumeration value="ANGRY2"/>
			<xs:enumeration value="STOP"/>
			<xs:enumeration value="SPEAK"/>
			<xs:enumeration value="LISTEN"/>
			<xs:enumeration value="SURPRISE"/>
            <xs:enumeration value="WHITE"/>
            <xs:enumeration value="RAINBOW"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="lightStateType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ON"/>
			<xs:enumeration value="OFF"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="lightRgbColorType">
		<xs:restriction base="xs:token">
			<xs:pattern value="#[\dA-F | a-f ]{6}([\dA-F | a-f][\dA-F | a-f])?"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="lightListColorType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="WHITE"/>
			<xs:enumeration value="BLACK"/>
			<xs:enumeration value="RED"/>
			<xs:enumeration value="PINK"/>
			<xs:enumeration value="GREEN"/>
			<xs:enumeration value="YELLOW"/>
			<xs:enumeration value="BLUE"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="lightColorType">
		<xs:union memberTypes="lightListColorType lightRgbColorType" />
	</xs:simpleType>

	<xs:simpleType name="counterOpType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="="/>
			<xs:enumeration value="+"/>
			<xs:enumeration value="*"/>
			<xs:enumeration value="/"/>
			<xs:enumeration value="%"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="evaEmotionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="NEUTRAL"/>
			<xs:enumeration value="HAPPY"/>
			<xs:enumeration value="SAD"/>
			<xs:enumeration value="ANGRY"/>
			<xs:enumeration value="FEAR"/>
			<xs:enumeration value="SURPRISE"/>
			<xs:enumeration value="INLOVE"/>
		</xs:restriction>
	</xs:simpleType>

  <!-- ** EvaML Commands Definitions ** -->

  <xs:element name="mqtt">
	<xs:complexType>
		<xs:attribute name="topic" type="topicType" use="required"/>
		<xs:attribute name="message" type="messageType" use="required"/>
	</xs:complexType>
</xs:element>

	<xs:element name="random">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="min" type="xs:nonNegativeInteger" use="required"/>
			<xs:attribute name="max" type="xs:nonNegativeInteger" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="wait">
	  <xs:complexType>
		<xs:attribute name="id" type="idType"/>
	    <xs:attribute name="duration" type="xs:nonNegativeInteger" use="required"/>
	  </xs:complexType>
	</xs:element>

	<xs:element name="talk">
		<xs:complexType mixed="true">
			<xs:attribute name="id" type="idType"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="stop">
		<xs:complexType>
		</xs:complexType>
	</xs:element>

	<xs:element name="light">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="state" type="lightStateType" use="required"/>
			<xs:attribute name="color" type="lightColorType" default="WHITE"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="goto">
		<xs:complexType>
			<xs:attribute name="target" type="xs:IDREF" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="userEmotion">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="evaEmotion">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="emotion" type="evaEmotionType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="useMacro">
		<xs:complexType>
			<xs:attribute name="macro" type="xs:IDREF" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="listen">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="audio">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="source" type="audioFileType" use="required"/>
			<xs:attribute name="block" type="audioBlockType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="led">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="animation" type="ledAnimationType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="counter">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="var" type="xs:string" use="required"/>
			<xs:attribute name="op" type="counterOpType" use="required"/>
			<xs:attribute name="value" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="switch">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="case" minOccurs="1" maxOccurs="unbounded" />
				<xs:element ref="default" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="var" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="motion">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="type" type="motionListType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="voice">
		<xs:complexType>
			<xs:attribute name="tone" type="voiceType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="lightEffects">
		<xs:complexType>
			<xs:attribute name="mode" type="modeType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="audioEffects">
		<xs:complexType>
			<xs:attribute name="mode" type="modeType" use="required"/>
			<xs:attribute name="vol" type="xs:string" default="100%"/>
		</xs:complexType>
	</xs:element>
    
	<xs:element name="loop">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="loop"/>
				<xs:element ref="mqtt"/>
				<xs:element ref="random"/>
				<xs:element ref="wait"/>
				<xs:element ref="talk"/>
				<xs:element ref="stop"/>
				<xs:element ref="light"/>
				<xs:element ref="goto"/>
				<xs:element ref="motion"/>
				<xs:element ref="userEmotion"/>
				<xs:element ref="evaEmotion"/>
				<xs:element ref="useMacro"/>
				<xs:element ref="listen"/>
				<xs:element ref="audio"/>
				<xs:element ref="led"/>
				<xs:element ref="counter"/>
				<xs:element ref="switch"/>
			</xs:choice>
			<xs:attribute name="id" type="idType"/>
		    <xs:attribute name="var" type="xs:string" use="optional"/>
		    <xs:attribute name="times" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="case">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="loop"/>
				<xs:element ref="mqtt"/>
				<xs:element ref="random"/>
				<xs:element ref="wait"/>
				<xs:element ref="talk"/>
				<xs:element ref="stop"/>
				<xs:element ref="light"/>
				<xs:element ref="goto"/>
				<xs:element ref="motion"/>
				<xs:element ref="userEmotion"/>
				<xs:element ref="evaEmotion"/>
				<xs:element ref="useMacro"/>
				<xs:element ref="listen"/>
				<xs:element ref="audio"/>
				<xs:element ref="led"/>
				<xs:element ref="counter"/>
				<xs:element ref="switch"/>
			</xs:choice>
			<xs:attribute name="op" type="caseOpType" use="required"/>
			<xs:attribute name="value" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="default">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="loop"/>
				<xs:element ref="mqtt"/>
				<xs:element ref="random"/>
				<xs:element ref="wait"/>
				<xs:element ref="talk"/>
				<xs:element ref="stop"/>
				<xs:element ref="light"/>
				<xs:element ref="goto"/>
				<xs:element ref="motion"/>
				<xs:element ref="userEmotion"/>
				<xs:element ref="evaEmotion"/>
				<xs:element ref="useMacro"/>
				<xs:element ref="listen"/>
				<xs:element ref="audio"/>
				<xs:element ref="led"/>
				<xs:element ref="counter"/>
				<xs:element ref="switch"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="macro">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="loop"/>
				<xs:element ref="mqtt"/>
				<xs:element ref="random"/>
				<xs:element ref="wait"/>
				<xs:element ref="talk"/>
				<xs:element ref="stop"/>
				<xs:element ref="light"/>
				<xs:element ref="goto"/>
				<xs:element ref="motion"/>
				<xs:element ref="userEmotion"/>
				<xs:element ref="evaEmotion"/>
				<xs:element ref="listen"/>
				<xs:element ref="audio"/>
				<xs:element ref="led"/>
				<xs:element ref="counter"/>
				<xs:element ref="switch"/>
			</xs:choice>
			<xs:attribute name="id" type="idType" use="required" />
		</xs:complexType>
	</xs:element>

	<!-- ** Root Section Definition ** -->
	<xs:element name="evaml">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="settings"/>
				<xs:element ref="script"/>
				<xs:element ref="macros" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<!-- ** Settings Section Definition ** -->
	<xs:element name="settings">
    <xs:complexType>
			<xs:all>
				<xs:element ref="voice" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="lightEffects" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="audioEffects" minOccurs="0" maxOccurs="1"/>
			</xs:all>
    </xs:complexType>
  </xs:element>

	<!-- ** Script Section Definition ** -->
	<xs:element name="script">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="loop"/>
				<xs:element ref="mqtt"/>
				<xs:element ref="random"/>
				<xs:element ref="wait"/>
				<xs:element ref="talk"/>
				<xs:element ref="stop"/>
				<xs:element ref="light"/>
				<xs:element ref="goto"/>
				<xs:element ref="motion"/>
				<xs:element ref="userEmotion"/>
				<xs:element ref="evaEmotion"/>
				<xs:element ref="useMacro"/>
				<xs:element ref="listen"/>
				<xs:element ref="audio"/>
				<xs:element ref="led"/>
				<xs:element ref="counter"/>
				<xs:element ref="switch"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<!-- ** Macros Section Definition ** -->
	<xs:element name="macros">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="macro"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== midiacom/eva-robot/EvaML-EvaSIM-source-code/Version1.0/demo_360_2023.xml
<?xml version="1.0" encoding="UTF-8"?>
<evaml
  name="demo_360_2023"
  xsi:noNamespaceSchemaLocation="EvaML-Schema/evaml_schema.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <settings>
    <voice tone="en-US_AllisonExpressive" />
    <lightEffects mode="ON" />
    <audioEffects mode="ON" />
  </settings>
  <script>
    <motion type="CENTER" />
    <evaEmotion emotion="NEUTRAL" />
    <light state="OFF" />
    <mqtt topic="FRED/pose" message="sad_foot_slow" />
    <mqtt topic="FRED/expression" message="broken" />
    <mqtt topic="FRED/leds" message="black" />
    <mqtt topic="FRED/expression" message="speech_off" />
    <wait duration="3000" />
    <light state="ON" color="YELLOW"/>
    <evaEmotion emotion="NEUTRAL" />
    <talk>Hello everyone, I am a social robot and my name is Eva</talk>
    <audio source="efx-wand1" block="TRUE" />
    <talk>I can comunicate using verbal and no verbal comunication</talk>
    <wait duration="1000" />
    <talk>I can control this smart bulb</talk>
    
    <light state="ON" color="RED"/>
    <audio source="efx-blin" block="TRUE" />
    <light state="ON" color="GREEN"/>
    <audio source="efx-blin" block="TRUE" />
    <light state="ON" color="BLUE"/>
    <audio source="efx-blin" block="TRUE" />
    <light state="ON" color="PINK"/>
    <audio source="efx-blin" block="TRUE" />

    <talk>I can be sad and I can demonstrate this using my facial expression</talk>
    <motion type="2DOWN" />
    <motion type="NO" />
    <light state="ON" color="BLUE"/>
    <evaEmotion emotion="SAD" />
    <led animation="SPEAK" />
    <audio source="song-ben" block="TRUE" />
    <led animation="STOP" />

    <motion type="CENTER" />
    <talk>I can be happy and I can demonstrate this using my facial expression</talk>
    <motion type="2UP" />
    <motion type="2UP" />
    <light state="ON" color="GREEN"/>
    <evaEmotion emotion="HAPPY" />
    <led animation="LISTEN" />
    <audio source="song-here-comes-the-sun" block="TRUE" />
    <led animation="STOP" />
    <motion type="CENTER" />
    <talk>I am happy because now I have new friends!</talk>
    <light state="ON" color="GREEN"/>
    <wait duration="2000" />
    <talk>Hello Fred!</talk>
    <motion type="2RIGHT" />
    <motion type="2RIGHT" />
    <evaEmotion emotion="NEUTRAL" />
    <mqtt topic="FRED/pose" message="neutral" />
    <mqtt topic="FRED/expression" message="neutral" />
    <mqtt topic="FRED/leds" message="black" />
    <wait duration="2000" />

    <talk>Hey Fred! Could you say something to the people?</talk>
    <mqtt topic="FRED_1021516/pose" message="left_foot1" />
    <wait duration="1000" />
    <mqtt topic="FRED_1021516/expression" message="speech_on" />
    <audio source="fred_speech1" block="TRUE" />
    <mqtt topic="FRED_1021516/expression" message="speech_off" />
    <wait duration="1400" />
    <mqtt topic="FRED_1021516/pose" message="neutral" />
    <wait duration="2000" />

    <mqtt topic="FRED_1021516/expression" message="happy" />
    <mqtt topic="FRED_1021516/leds" message="green" />
    <wait duration="1000" />
    <mqtt topic="FRED_1021516/expression" message="speech_on" />
    <audio source="fred_speech2" block="TRUE" />
    <mqtt topic="FRED_1021516/expression" message="speech_off" />
    <wait duration="1400" />
    <mqtt topic="FRED_1021516/pose" message="tiptoe_foot" />
    <wait duration="2000" />

    <mqtt topic="FRED_14194525/pose" message="tiptoe_foot" />
    <mqtt topic="FRED_14194525/leds" message="green" />
    <wait duration="1000" />
    <mqtt topic="FRED_14194525/expression" message="speech_on" />
    <audio source="frida_speech1" block="TRUE" />
    <mqtt topic="FRED_14194525/expression" message="speech_off" />
    <wait duration="1400" />

    <audio source="song-careless" block="FALSE" />
    <mqtt topic="FRED_1021516/expression" message="in_love" />
    <mqtt topic="FRED_1021516/pose" message="broken" />
    <mqtt topic="FRED_1021516/leds" message="red" />
    <mqtt topic="FRED_14194525/expression" message="in_love" />
    <mqtt topic="FRED/leds" message="rainbow" />
    <wait duration="14000" />

    <mqtt topic="FRED_14194525/expression" message="happy" />
    <mqtt topic="FRED_14194525/expression" message="speech_on" />
    <audio source="frida_speech3" block="TRUE" />
    <mqtt topic="FRED_14194525/expression" message="speech_off" />
    <wait duration="2000" />
    
    <mqtt topic="FRED_1021516/expression" message="happy" />
    <mqtt topic="FRED_1021516/expression" message="speech_on" />
    <audio source="fred_speech3" block="TRUE" />
    <mqtt topic="FRED_1021516/expression" message="speech_off" />
    <wait duration="1400" />

    <motion type="CENTER" />

    <motion type="2UP" />
    <evaEmotion emotion="HAPPY" />
    <led animation="RAINBOW" />

    <audio source="song-take-on-me" block="FALSE" />
    <mqtt topic="FRED/leds" message="happy" />
    <mqtt topic="FRED/expression" message="happy" />

    <mqtt topic="FRED_1021516/move" message="dance1_1" />
    <mqtt topic="FRED_1021516/move" message="moonwalk2" />

    <mqtt topic="FRED_14194525/move" message="dance1_2" />
    <mqtt topic="FRED_14194525/move" message="dance2_2" />

    <wait duration="12000" />
  
    <evaEmotion emotion="NEUTRAL" />
    <mqtt topic="FRED/pose" message="tiptoe_foot" />
    <light state="OFF" />
  </script>
</evaml>

=== midiacom/eva-robot/EvaML-EvaSIM-source-code/Version1.0/_macros.xml
<evaml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="teste_talk" xsi:noNamespaceSchemaLocation="EvaML-Schema/evaml_schema.xsd">
  <settings>
    <voice tone="pt-BR_IsabelaV3Voice" />
    <lightEffects mode="ON" />
    <audioEffects mode="ON" />
  </settings>
  <script>
    <light state="ON" color="GREEN" />
    <evaEmotion emotion="HAPPY" />
  </script>
</evaml>

=== midiacom/eva-robot/EvaML-EvaSIM-source-code/Version1.0/teste.xml
<?xml version="1.0" encoding="UTF-8"?>
<evaml
  name="teste"
  xsi:noNamespaceSchemaLocation="EvaML-Schema/evaml_schema.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <settings>
    <voice tone="pt-BR_IsabelaV3Voice" />
    <lightEffects mode="ON" />
    <audioEffects mode="ON" />
  </settings>
  <script>
    <motion type="CENTER" />
    <light state="ON" color="WHITE" />
    <evaEmotion emotion="NEUTRAL" />
    <audio source="efx-wand1" block="TRUE" />
    <talk>Olá, eu sou a nova versão do robô EVA</talk>
    <wait duration="1000" />
    <talk>Tenho um novo sistema de controle totalmente modular e feito em Páiton</talk>
    <wait duration="1000" />
    <talk>isso permite a adição de novas funcionalidades ao meu sistema </talk>
    <wait duration="1000" />
    <talk>todas essas funcionalidades são controladas através de mensagens MQTT</talk>
    <motion type="2LEFT" />
    <motion type="DOWN" />
    <wait duration="1000" />
    <light state="ON" color="GREEN" />
    <talk>Neste momento, estou executando um script feito na linguagem Eva ML e que está sendo executado no simulador Eva SIM</talk>
    <motion type="2RIGHT" />
    <motion type="DOWN" />
    <wait duration="1000" />
    <talk>Quando falo, a luz no meu peito fica azul automaticamente</talk>
    <motion type="CENTER" />
    <wait duration="1000" />
    <talk>Também ganhei um novo visual no meu displey</talk>
    <wait duration="1000" />
    <talk>Meu olhar é renderizado em uma janela usando guifs</talk>
    <wait duration="1000" />
    <talk>Além do novo visual, também ganhei novas emoções</talk>
    <wait duration="1000" />
    <motion type="CENTER" />
    <talk>Quando estou neutro</talk>
    <wait duration="400" />
    <talk>Como agora</talk>
    <wait duration="1000" />
    <talk>meus olhos podem piscar aleatoriamente</talk>
    <wait duration="2000" />
    <motion type="UP" />

    <talk>Além de poder ficar feliz</talk>
    <evaEmotion emotion="HAPPY" />
    <led animation="HAPPY" />
    <motion type="2UP" />
    <audio source="song-here-comes-the-sun" block="TRUE" />

    <talk>Triste</talk>
    <motion type="2DOWN" />
    <motion type="2DOWN" />
    <evaEmotion emotion="SAD" />
    <led animation="SAD" />
    <light state="ON" color="BLUE" />
    <audio source="song-ben" block="TRUE" />

    <talk>e com raiva</talk>
    <motion type="NO" />
    <evaEmotion emotion="ANGRY" />
    <led animation="ANGRY" />
    <light state="ON" color="RED" />
    <audio source="song-mj-thriller2" block="TRUE" />
    <motion type="CENTER" />

    <talk>Também posso ficar com medo</talk>
    <evaEmotion emotion="FEAR" />
    <led animation="SAD" />
    <audio source="song-fear" block="TRUE" />

    <talk>e surpreso</talk>
    <evaEmotion emotion="SURPRISE" />
    <led animation="SURPRISE" />
    <light state="ON" color="YELLOW" />
    <audio source="song-surprise" block="TRUE" />

    <led animation="STOP" />
    <evaEmotion emotion="NEUTRAL" />
    <motion type="2LEFT" />
    <motion type="UP" />
    <motion type="LEFT" />
    <talk>Continuo podendo controlar esta lâmpada inteligente</talk>
    <light state="ON" color="WHITE" />
    <wait duration="1200" />
    <light state="ON" color="RED" />
    <wait duration="1200" />
    <light state="ON" color="BLUE" />
    <wait duration="1200" />
    <light state="ON" color="GREEN" />
    <wait duration="1200" />
    <motion type="CENTER" />
    <talk>e como você deve ter percebido, também estou movendo minha cabeça</talk>
    <wait duration="2000" />
    <talk>Vou tocar uma música para encerrar</talk>
    <evaEmotion emotion="HAPPY" />
    <motion type="UP" />
    <motion type="NO" />
    <led animation="RAINBOW" />
    <audio source="song-the-girl-from-ipanema" block="TRUE" />

    <led animation="STOP" />
    <light state="OFF" />
    <motion type="CENTER" />
  </script>
</evaml>

=== midiacom/eva-robot/EvaML-EvaSIM-source-code/Version1.0/teste_talk.xml
<?xml version="1.0" encoding="UTF-8"?>
<evaml
  name="teste_talk"
  xsi:noNamespaceSchemaLocation="EvaML-Schema/evaml_schema.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <settings>
    <voice tone="pt-BR_IsabelaV3Voice" />
    <lightEffects mode="ON" />
    <audioEffects mode="ON" />
  </settings>
  <script>
    <light state="ON" color="GREEN"/>
    <evaEmotion emotion="HAPPY" />
  </script>
</evaml>

=== midiacom/eva-robot/EvaML-EvaSIM-source-code/Version1.0/xmls_para_teste/case_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<evaml
  name="case_1"
  xsi:noNamespaceSchemaLocation="EvaML-Schema/evaml_schema.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <settings>
    <voice tone="pt-BR_IsabelaV3Voice" />
    <lightEffects mode="ON" />
    <audioEffects mode="ON" />
  </settings>
  <script>
   <loop times="2">
    <led animation="HAPPY" />
   </loop>
  </script>
</evaml>
