=== midiacom/eva-robot/EvaML-EvaSIM-source-code/Version1.0/EvaML-Schema/evaml_schema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<!--
XML Schema for the EvaML Language
This is EvaML
Copyright : 2022 LABORATORIO MIDIACOM, All Rights Reserved.
See https://www.midiacom.uff.br
PublicURI : https://github.com/midiacom/eva-robot/blob/master/EvaML-EvaSIM-source-code/Linux%20Version/EvaML-Schema/evaml_schema.xsd
Author : Marcelo Marques da Rocha
Revision: 2022/08/12
-->
  <!-- ** Data type definitions ** -->
	<xs:simpleType name="idType">
		<xs:restriction base="xs:ID"/>
	</xs:simpleType>

	<xs:simpleType name="modeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ON"/>
			<xs:enumeration value="OFF"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="voiceListType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="pt-BR_IsabelaV3Voice"/>
			<xs:enumeration value="en-US_AllisonV3Voice"/> 
			<xs:enumeration value="en-US_AllisonExpressive"/> 
			<xs:enumeration value="en-US_EmmaExpressive"/>
			<xs:enumeration value="en-US_LisaExpressive"/>
			<xs:enumeration value="en-US_MichaelExpressive"/>
			<xs:enumeration value="en-US_MichaelV3Voice"/>
			<xs:enumeration value="en-US_KevinV3Voice"/>
			<xs:enumeration value="en-US_OliviaV3Voice"/>
			<xs:enumeration value="en-US_EmilyV3Voice"/>
			<xs:enumeration value="en-US_HenryV3Voice"/>
			<xs:enumeration value="es-LA_SofiaV3Voice"/>
			<xs:enumeration value="es-ES_LauraV3Voice"/>
			<xs:enumeration value="es-ES_EnriqueV3Voice"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="motionListType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="YES"/>
			<xs:enumeration value="NO"/>
			<xs:enumeration value="CENTER"/>
			<xs:enumeration value="LEFT"/>
			<xs:enumeration value="RIGHT"/>
			<xs:enumeration value="UP"/>
			<xs:enumeration value="DOWN"/>
			<xs:enumeration value="2UP"/>
			<xs:enumeration value="2DOWN"/>
			<xs:enumeration value="2RIGHT"/>
			<xs:enumeration value="2LEFT"/>
			<xs:enumeration value="DOWN_RIGHT"/>
			<xs:enumeration value="2DOWN_RIGHT"/>
			<xs:enumeration value="DOWN_LEFT"/>
			<xs:enumeration value="2DOWN_LEFT"/>
			<xs:enumeration value="UP_RIGHT"/>
			<xs:enumeration value="2UP_RIGHT"/>
			<xs:enumeration value="UP_LEFT"/>
			<xs:enumeration value="2UP_LEFT"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="voiceStringType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>

	<xs:simpleType name="voiceType">
		<xs:union memberTypes="voiceListType voiceStringType" />
	</xs:simpleType>

	<xs:simpleType name="topicType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>

	<xs:simpleType name="messageType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>

	<xs:simpleType name="audioListType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="efx-blin"/>
            <xs:enumeration value="efx-cheering"/>
            <xs:enumeration value="efx-crowdapplause1"/>
            <xs:enumeration value="efx-fanfare"/>
            <xs:enumeration value="efx-mario-end-01"/>
            <xs:enumeration value="efx-mario-end-02"/>
            <xs:enumeration value="efx-mario-end-03"/>
            <xs:enumeration value="efx-mario-fundo"/>
            <xs:enumeration value="efx-mario-game-intro"/>
            <xs:enumeration value="efx-mario-sound1-longo"/>
            <xs:enumeration value="efx-mario-sound1"/>
            <xs:enumeration value="efx-mario-sound2"/>
            <xs:enumeration value="efx-mario-start-01"/>
            <xs:enumeration value="efx-mario-start-02"/>
            <xs:enumeration value="efx-tic-toc"/>
            <xs:enumeration value="efx-wand1"/>
            <xs:enumeration value="MUTED-SOUND"/>
            <xs:enumeration value="song-ben"/>
            <xs:enumeration value="song-caneta-azul"/>
            <xs:enumeration value="song-exodus"/>
            <xs:enumeration value="song-mj-heal-the-world"/>
            <xs:enumeration value="song-here-comes-the-sun"/>
            <xs:enumeration value="song-mj-heal-the-world"/>
            <xs:enumeration value="song-mj-thriller2"/>
            <xs:enumeration value="song-mj-thriller3-laugh"/>
            <xs:enumeration value="song-oh-no"/>
            <xs:enumeration value="song-take-on-me"/>
            <xs:enumeration value="song-the-girl-from-ipanema"/>
            <xs:enumeration value="song-the-imperial-march"/>
            <xs:enumeration value="song-thriller-open"/>
            <xs:enumeration value="song-vivaldi-spring"/>
            <xs:enumeration value="song-weird-science"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="audioStringType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>

	<xs:simpleType name="audioFileType">
		<xs:union memberTypes="audioListType audioStringType" />
	</xs:simpleType>

	<xs:simpleType name="caseOpType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="exact"/>
			<xs:enumeration value="contain"/>
			<xs:enumeration value="eq"/>
			<xs:enumeration value="lt"/>
			<xs:enumeration value="gt"/>
			<xs:enumeration value="lte"/>
			<xs:enumeration value="gte"/>
			<xs:enumeration value="ne"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="audioBlockType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="TRUE"/>
			<xs:enumeration value="FALSE"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="ledAnimationType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="HAPPY"/>
			<xs:enumeration value="SAD"/>
			<xs:enumeration value="ANGRY"/>
            <xs:enumeration value="ANGRY2"/>
			<xs:enumeration value="STOP"/>
			<xs:enumeration value="SPEAK"/>
			<xs:enumeration value="LISTEN"/>
			<xs:enumeration value="SURPRISE"/>
            <xs:enumeration value="WHITE"/>
            <xs:enumeration value="RAINBOW"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="lightStateType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ON"/>
			<xs:enumeration value="OFF"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="lightRgbColorType">
		<xs:restriction base="xs:token">
			<xs:pattern value="#[\dA-F | a-f ]{6}([\dA-F | a-f][\dA-F | a-f])?"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="lightListColorType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="WHITE"/>
			<xs:enumeration value="BLACK"/>
			<xs:enumeration value="RED"/>
			<xs:enumeration value="PINK"/>
			<xs:enumeration value="GREEN"/>
			<xs:enumeration value="YELLOW"/>
			<xs:enumeration value="BLUE"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="lightColorType">
		<xs:union memberTypes="lightListColorType lightRgbColorType" />
	</xs:simpleType>

	<xs:simpleType name="counterOpType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="="/>
			<xs:enumeration value="+"/>
			<xs:enumeration value="*"/>
			<xs:enumeration value="/"/>
			<xs:enumeration value="%"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="evaEmotionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="NEUTRAL"/>
			<xs:enumeration value="HAPPY"/>
			<xs:enumeration value="SAD"/>
			<xs:enumeration value="ANGRY"/>
			<xs:enumeration value="FEAR"/>
			<xs:enumeration value="SURPRISE"/>
			<xs:enumeration value="INLOVE"/>
		</xs:restriction>
	</xs:simpleType>

  <!-- ** EvaML Commands Definitions ** -->

  <xs:element name="mqtt">
	<xs:complexType>
		<xs:attribute name="topic" type="topicType" use="required"/>
		<xs:attribute name="message" type="messageType" use="required"/>
	</xs:complexType>
</xs:element>

	<xs:element name="random">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="min" type="xs:nonNegativeInteger" use="required"/>
			<xs:attribute name="max" type="xs:nonNegativeInteger" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="wait">
	  <xs:complexType>
		<xs:attribute name="id" type="idType"/>
	    <xs:attribute name="duration" type="xs:nonNegativeInteger" use="required"/>
	  </xs:complexType>
	</xs:element>

	<xs:element name="talk">
		<xs:complexType mixed="true">
			<xs:attribute name="id" type="idType"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="stop">
		<xs:complexType>
		</xs:complexType>
	</xs:element>

	<xs:element name="light">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="state" type="lightStateType" use="required"/>
			<xs:attribute name="color" type="lightColorType" default="WHITE"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="goto">
		<xs:complexType>
			<xs:attribute name="target" type="xs:IDREF" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="userEmotion">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="evaEmotion">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="emotion" type="evaEmotionType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="useMacro">
		<xs:complexType>
			<xs:attribute name="macro" type="xs:IDREF" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="listen">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="audio">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="source" type="audioFileType" use="required"/>
			<xs:attribute name="block" type="audioBlockType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="led">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="animation" type="ledAnimationType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="counter">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="var" type="xs:string" use="required"/>
			<xs:attribute name="op" type="counterOpType" use="required"/>
			<xs:attribute name="value" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="switch">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="case" minOccurs="1" maxOccurs="unbounded" />
				<xs:element ref="default" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="var" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="motion">
		<xs:complexType>
			<xs:attribute name="id" type="idType"/>
			<xs:attribute name="type" type="motionListType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="voice">
		<xs:complexType>
			<xs:attribute name="tone" type="voiceType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="lightEffects">
		<xs:complexType>
			<xs:attribute name="mode" type="modeType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="audioEffects">
		<xs:complexType>
			<xs:attribute name="mode" type="modeType" use="required"/>
			<xs:attribute name="vol" type="xs:string" default="100%"/>
		</xs:complexType>
	</xs:element>
    
	<xs:element name="loop">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="loop"/>
				<xs:element ref="mqtt"/>
				<xs:element ref="random"/>
				<xs:element ref="wait"/>
				<xs:element ref="talk"/>
				<xs:element ref="stop"/>
				<xs:element ref="light"/>
				<xs:element ref="goto"/>
				<xs:element ref="motion"/>
				<xs:element ref="userEmotion"/>
				<xs:element ref="evaEmotion"/>
				<xs:element ref="useMacro"/>
				<xs:element ref="listen"/>
				<xs:element ref="audio"/>
				<xs:element ref="led"/>
				<xs:element ref="counter"/>
				<xs:element ref="switch"/>
			</xs:choice>
			<xs:attribute name="id" type="idType"/>
		    <xs:attribute name="var" type="xs:string" use="optional"/>
		    <xs:attribute name="times" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="case">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="loop"/>
				<xs:element ref="mqtt"/>
				<xs:element ref="random"/>
				<xs:element ref="wait"/>
				<xs:element ref="talk"/>
				<xs:element ref="stop"/>
				<xs:element ref="light"/>
				<xs:element ref="goto"/>
				<xs:element ref="motion"/>
				<xs:element ref="userEmotion"/>
				<xs:element ref="evaEmotion"/>
				<xs:element ref="useMacro"/>
				<xs:element ref="listen"/>
				<xs:element ref="audio"/>
				<xs:element ref="led"/>
				<xs:element ref="counter"/>
				<xs:element ref="switch"/>
			</xs:choice>
			<xs:attribute name="op" type="caseOpType" use="required"/>
			<xs:attribute name="value" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="default">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="loop"/>
				<xs:element ref="mqtt"/>
				<xs:element ref="random"/>
				<xs:element ref="wait"/>
				<xs:element ref="talk"/>
				<xs:element ref="stop"/>
				<xs:element ref="light"/>
				<xs:element ref="goto"/>
				<xs:element ref="motion"/>
				<xs:element ref="userEmotion"/>
				<xs:element ref="evaEmotion"/>
				<xs:element ref="useMacro"/>
				<xs:element ref="listen"/>
				<xs:element ref="audio"/>
				<xs:element ref="led"/>
				<xs:element ref="counter"/>
				<xs:element ref="switch"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="macro">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="loop"/>
				<xs:element ref="mqtt"/>
				<xs:element ref="random"/>
				<xs:element ref="wait"/>
				<xs:element ref="talk"/>
				<xs:element ref="stop"/>
				<xs:element ref="light"/>
				<xs:element ref="goto"/>
				<xs:element ref="motion"/>
				<xs:element ref="userEmotion"/>
				<xs:element ref="evaEmotion"/>
				<xs:element ref="listen"/>
				<xs:element ref="audio"/>
				<xs:element ref="led"/>
				<xs:element ref="counter"/>
				<xs:element ref="switch"/>
			</xs:choice>
			<xs:attribute name="id" type="idType" use="required" />
		</xs:complexType>
	</xs:element>

	<!-- ** Root Section Definition ** -->
	<xs:element name="evaml">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="settings"/>
				<xs:element ref="script"/>
				<xs:element ref="macros" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<!-- ** Settings Section Definition ** -->
	<xs:element name="settings">
    <xs:complexType>
			<xs:all>
				<xs:element ref="voice" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="lightEffects" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="audioEffects" minOccurs="0" maxOccurs="1"/>
			</xs:all>
    </xs:complexType>
  </xs:element>

	<!-- ** Script Section Definition ** -->
	<xs:element name="script">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="loop"/>
				<xs:element ref="mqtt"/>
				<xs:element ref="random"/>
				<xs:element ref="wait"/>
				<xs:element ref="talk"/>
				<xs:element ref="stop"/>
				<xs:element ref="light"/>
				<xs:element ref="goto"/>
				<xs:element ref="motion"/>
				<xs:element ref="userEmotion"/>
				<xs:element ref="evaEmotion"/>
				<xs:element ref="useMacro"/>
				<xs:element ref="listen"/>
				<xs:element ref="audio"/>
				<xs:element ref="led"/>
				<xs:element ref="counter"/>
				<xs:element ref="switch"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<!-- ** Macros Section Definition ** -->
	<xs:element name="macros">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="macro"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== midiacom/eva-robot/EvaML-EvaSIM-source-code/Version1.0/xmls_para_teste/demo_360.xml
<?xml version="1.0" encoding="UTF-8"?>
<evaml
  name="demo_360"
  xsi:noNamespaceSchemaLocation="EvaML-Schema/evaml_schema.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <settings>
    <voice tone="pt-BR_IsabelaV3Voice" />
    <lightEffects mode="ON" />
    <audioEffects mode="ON" />
  </settings>
  <script>
    <!-- Variaveis do script -->
    <light state="ON" />
    <evaEmotion emotion="NEUTRAL" />
    <counter var="PONTOS" op="=" value="0" />
    <counter var="ERRO1" op="=" value="0" />
    <counter var="ERRO2" op="=" value="0" />
    <motion type="CENTER" />
    <audio source="Wand1" block="TRUE" />
    <talk>Eu sou o robô eva</talk>
    <audio source="Blin" block="TRUE" />
    <talk>Como você se chama?</talk>
    <listen /> <!-- $1 é nome do usuário -->
    <evaEmotion emotion="HAPPY" />
    <light state="ON" color="GREEN"/>
    <talk>Oi $</talk>
    <talk>Vamos jogar o jogo das tabuadas</talk>
    <audio source="mario-game-intro" block="TRUE" />
    <talk>Eu vou te fazer duas perguntas e você tenta acertar</talk>
    <evaEmotion emotion="NEUTRAL" />
    <talk>Vamos para a primeira pergunta</talk>
    <light state="ON" />
    <motion type="2DOWN" />
    <audio source="Blin" block="TRUE" />
    <!-- Primeira pergunta com tabuadas de 2 a 5 -->
    <random min="2" max="5" /> 
    <switch var="$">
      <!-- TABUADA de 2 -->
      <case op="exact" value="2">
        <talk>Quanto é dois vezes cinco?</talk>
        <listen />
        <switch var="$">
          <case op="exact" value="10">
            <motion type="2UP" />
            <evaEmotion emotion="HAPPY" />
            <counter var="PONTOS" op="+" value="1" />
            <audio source="mario-start-02" block="TRUE" /> <!-- som de vitória -->
            <light state="ON" color="GREEN"/>
            <talk>Muito bem! Você acertou!</talk>
          </case>
          <default>
            <motion type="NO" />
            <evaEmotion emotion="SAD" />
            <counter var="ERRO1" op="=" value="2" />
            <light state="ON" color="BLUE"/>
            <talk>Puxa, não foi dessa vez. Você precisa estudar mais um pouco</talk>
          </default>
        </switch>
      </case>
      <!-- TABUADA de 3 -->
      <case op="exact" value="3">
        <talk>Quanto é três vezes seis?</talk>
        <listen />
        <switch var="$">
          <case op="exact" value="18">
            <motion type="2UP" />
            <evaEmotion emotion="HAPPY" />
            <counter var="PONTOS" op="+" value="1" />
            <audio source="mario-start-02" block="TRUE" /> <!-- som de vitória -->
            <light state="ON" color="GREEN"/>
            <talk>Muito bem! Você acertou!</talk>
          </case>
          <default>
            <motion type="NO" />
            <evaEmotion emotion="SAD" />
            <counter var="ERRO1" op="=" value="3" />
            <light state="ON" color="BLUE"/>
            <talk>Puxa, não foi dessa vez. Você precisa estudar mais um pouco</talk>
          </default>
        </switch>
      </case>
      <!-- TABUADA de 4 -->
      <case op="exact" value="4">
        <talk>Quanto é quatro vezes cinco?</talk>
        <listen />
        <switch var="$">
          <case op="exact" value="20">
            <motion type="2UP" />
            <evaEmotion emotion="HAPPY" />
            <counter var="PONTOS" op="+" value="1" />
            <audio source="mario-start-02" block="TRUE" /> <!-- som de vitória -->
            <light state="ON" color="GREEN"/>
            <talk>Muito bem! Você acertou!</talk>
          </case>
          <default>
            <motion type="NO" />
            <evaEmotion emotion="SAD" />
            <counter var="ERRO1" op="=" value="4" />
            <light state="ON" color="BLUE"/>
            <talk>Puxa, não foi dessa vez. Você precisa estudar mais um pouco</talk>
          </default>
        </switch>
      </case>
      <!-- TABUADA de 5 -->
      <case op="exact" value="5">
        <talk>Quanto é cinco vezes oito?</talk>
        <listen />
        <switch var="$">
          <case op="exact" value="40">
            <motion type="2UP" />
            <evaEmotion emotion="HAPPY" />
            <counter var="PONTOS" op="+" value="1" />
            <audio source="mario-start-02" block="TRUE" /> <!-- som de vitória -->
            <light state="ON" color="GREEN"/>
            <talk>Muito bem! Você acertou!</talk>
          </case>
          <default>
            <motion type="NO" />
            <evaEmotion emotion="SAD" />
            <counter var="ERRO1" op="=" value="5" />
            <light state="ON" color="BLUE"/>
            <talk>Puxa, não foi dessa vez. Você precisa estudar mais um pouco</talk>
          </default>
        </switch>
      </case>
    </switch>
    <light state="ON" />
    <motion type="CENTER" />
    <evaEmotion emotion="NEUTRAL" />
    <talk>Vamos para a segunda pergunta</talk>
    <evaEmotion emotion="HAPPY" />
    <led animation="LISTEN" />
    <light state="ON" color="GREEN"/>
    <wait duration="10000" />
    <audio source="Blin" block="TRUE" />
    <!-- Segunda pergunta com tabuadas de 6 a 9 -->
    <random min="6" max="9" /> 
    <motion type="2DOWN" />
    <switch var="$">
      <!-- TABUADA de 6 -->
      <case op="exact" value="6">
        <talk>Quanto é seis vezes sete?</talk>
        <listen />
        <switch var="$">
          <case op="exact" value="42">
            <motion type="2UP" />
            <evaEmotion emotion="HAPPY" />
            <counter var="PONTOS" op="+" value="2" />
            <audio source="mario-start-02" block="TRUE" /> <!-- som de vitória -->
            <light state="ON" color="GREEN"/>
            <talk>Muito bem! Você acertou!</talk>
          </case>
          <default>
            <motion type="NO" />
            <evaEmotion emotion="SAD" />
            <counter var="ERRO2" op="=" value="6" />
            <light state="ON" color="BLUE"/>
            <talk>Puxa, não foi dessa vez. Você precisa estudar mais um pouco</talk>
          </default>
        </switch>
      </case>
      <!-- TABUADA de 7 -->
      <case op="exact" value="7">
        <talk>Quanto é sete vezes nove?</talk>
        <listen />
        <switch var="$">
          <case op="exact" value="63">
            <motion type="2UP" />
            <evaEmotion emotion="HAPPY" />
            <counter var="PONTOS" op="+" value="2" />
            <audio source="mario-start-02" block="TRUE" /> <!-- som de vitória -->
            <light state="ON" color="GREEN"/>
            <talk>Muito bem! Você acertou!</talk>
          </case>
          <default>
            <motion type="NO" />
            <evaEmotion emotion="SAD" />
            <counter var="ERRO2" op="=" value="7" />
            <light state="ON" color="BLUE"/>
            <talk>Puxa, não foi dessa vez. Você precisa estudar mais um pouco</talk>
          </default>
        </switch>
      </case>
      <!-- TABUADA de 8 -->
      <case op="exact" value="8">
        <talk>Quanto é oito vezes nove?</talk>
        <listen />
        <switch var="$">
          <case op="exact" value="72">
            <motion type="2UP" />
            <evaEmotion emotion="HAPPY" />
            <counter var="PONTOS" op="+" value="2" />
            <audio source="mario-start-02" block="TRUE" /> <!-- som de vitória -->
            <light state="ON" color="GREEN"/>
            <talk>Muito bem! Você acertou!</talk>
          </case>
          <default>
            <motion type="NO" />
            <evaEmotion emotion="SAD" />
            <counter var="ERRO2" op="=" value="8" />
            <light state="ON" color="BLUE"/>
            <talk>Puxa, não foi dessa vez. Você precisa estudar mais um pouco</talk>
          </default>
        </switch>
      </case>
      <!-- TABUADA de 9 -->
      <case op="exact" value="9">
        <talk>Quanto é nove vezes seis?</talk>
        <listen />
        <switch var="$">
          <case op="exact" value="54">
            <motion type="2UP" />
            <evaEmotion emotion="HAPPY" />
            <counter var="PONTOS" op="+" value="2" />
            <audio source="mario-start-02" block="TRUE" /> <!-- som de vitória -->
            <light state="ON" color="GREEN"/>
            <talk>Muito bem! Você acertou!</talk>
          </case>
          <default>
            <motion type="NO" />
            <evaEmotion emotion="SAD" />
            <counter var="ERRO2" op="=" value="9" />
            <light state="ON" color="BLUE"/>
            <talk>Puxa, não foi dessa vez. Você precisa estudar mais um pouco</talk>
          </default>
        </switch>
      </case>
    </switch>
    <evaEmotion emotion="HAPPY" />
    <light state="ON" color="PINK"/>
    <motion type="CENTER" />
    <switch var="PONTOS">
      <case op="eq" value="0"> <!-- não acertou nenhuma -->
        <talk>Foi muito bom jogar com você</talk>
        <talk>Mas você precisa praticar mais as tabuadas de #ERRO1 e de #ERRO2</talk>
        <talk>Bons estudos e até mais</talk>
      </case>
      <case op="eq" value="1"> <!-- só acertou a primeira -->
        <talk>Meus parabéns, você fez um ponto</talk>
        <talk>Você precisa praticar mais a tabuada de #ERRO2</talk>
        <talk>Foi muito bom jogar com você. Até mais</talk>
      </case>
      <case op="eq" value="2"> <!-- só acertou a segunda -->
        <talk>Meus parabéns, você fez um ponto</talk>
        <talk>Você precisa praticar mais a tabuada de #ERRO1</talk>
        <talk>Foi muito bom jogar com você. Até mais</talk>
      </case>
      <case op="eq" value="3"> <!-- acertou as duas pergntas -->
        <motion type="2UP" />
        <talk>Meus parabéns, você acertou as duas perguntas e fez dois pontos</talk>
        <talk>Foi muito bom jogar com você. Até mais</talk>
      </case>
    </switch>
    <!-- FINAL -->
    <motion type="CENTER" />
    <evaEmotion emotion="NEUTRAL" />
    <audio source="mario-end-02" block="TRUE" />
    <light state="OFF" />
  </script>
</evaml>

=== midiacom/eva-robot/EvaML-EvaSIM-source-code/Version1.0/teste_listen.xml
<?xml version="1.0" encoding="UTF-8"?>
<evaml
  name="teste_listen"
  xsi:noNamespaceSchemaLocation="EvaML-Schema/evaml_schema.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <settings>
    <voice tone="pt-BR_IsabelaV3Voice" />
    <lightEffects mode="ON" />
    <audioEffects mode="ON" />
  </settings>
  <script>
    <light state="ON" color="GREEN"/>
    <evaEmotion emotion="HAPPY" />
    <talk>Qual o seu nome?</talk>
    <listen />
    <light state="OFF" color="BLACK"/>
    <talk>Muito prazer em conhecÃª-lo $</talk>
  </script>
</evaml>

=== midiacom/eva-robot/EvaML-EvaSIM-source-code/Version1.0/_node_keys.xml
<evaml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="case_5" xsi:noNamespaceSchemaLocation="EvaML-Schema/evaml_schema.xsd" id="89432b7b3ca9c342a2ba43358ce506a0">
  <settings>
    <voice tone="pt-BR_IsabelaV3Voice" key="1000" />
    <lightEffects mode="ON" />
    <audioEffects mode="ON" />
  </settings>
  <script>
    <random id="loop" min="1" max="4" key="1001" />
    <wait duration="1000" key="1002" />
    <switch var="$">
      <case op="eq" value="1" key="1003" child_proc="false">
        <led animation="HAPPY" key="1004" />
      </case>
      <case op="eq" value="2" key="1005" child_proc="false">
        <led animation="SAD" key="1006" />
      </case>
      <case op="eq" value="3" key="1007" child_proc="false">
        <led animation="ANGRY" key="1008" />
      </case>
      <default key="1009" child_proc="false">
        <stop />
      </default>
    </switch>
    <goto target="loop" />
  </script>
</evaml>

=== midiacom/eva-robot/EvaML-EvaSIM-source-code/Version1.0/case_5.xml
<?xml version="1.0" encoding="UTF-8"?>
<evaml
  name="case_5"
  xsi:noNamespaceSchemaLocation="EvaML-Schema/evaml_schema.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <settings>
    <voice tone="pt-BR_IsabelaV3Voice" />
    <lightEffects mode="ON" />
    <audioEffects mode="ON" />
  </settings>
  <script>
    <random id="loop" min="1" max="4" />
    <wait duration="1000" />
    <switch var="$">
      <case op="eq" value="1">
        <led animation="HAPPY" />
      </case>
      <case op="eq" value="2">
        <led animation="SAD" />
      </case>
      <case op="eq" value="3">
        <led animation="ANGRY" />
      </case>
      <default>
        <stop/>
      </default>
    </switch>
    <goto target="loop" />
  </script>
</evaml>

=== midiacom/eva-robot/EvaML-EvaSIM-source-code/Version1.0/case_4.xml
<?xml version="1.0" encoding="UTF-8"?>
<evaml
  name="case_4"
  xsi:noNamespaceSchemaLocation="EvaML-Schema/evaml_schema.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <settings>
    <voice tone="pt-BR_IsabelaV3Voice" />
    <lightEffects mode="ON" />
    <audioEffects mode="ON" />
  </settings>
  <script>
    <random min="1" max="4" />
    <switch var="$" id="loop">
      <case op="eq" value="1">
        <led animation="HAPPY" />
      </case>
      <case op="eq" value="2">
        <led animation="SAD" />
      </case>
      <case op="eq" value="3">
        <led animation="ANGRY" />
      </case>
      <default>
        <stop/>
      </default>
    </switch>
    <wait duration="1000" />
    <random min="1" max="4" />
    <goto target="loop" />
  </script>
</evaml>
